### ISSUE TITLE
Premium search error 422

### ISSUE THREAD

**Issue by peiyaoli2** [geduldig/TwitterAPI#102]
Hi, when I try to use the premium search feature, I get this error:

`Traceback (most recent call last):
  File "twitter_premium.py", line 19, in <module>
    for item in r:
  File "C:\ProgramData\Anaconda3\lib\site-packages\TwitterAPI\TwitterAPI.py", li
ne 206, in __iter__
    return self.get_iterator()
  File "C:\ProgramData\Anaconda3\lib\site-packages\TwitterAPI\TwitterAPI.py", li
ne 193, in get_iterator
    raise TwitterRequestError(self.response.status_code)
TwitterAPI.TwitterError.TwitterRequestError: Twitter request failed (422)`

Also, I'm wondering if I can use other parameters like specifying start dates and end dates with the premium API.

One more question: TwitterPager seems to give the same error as well, something with the iterator

**Comment by peiyaoli2** [comment]
Update: so I don't get the 422 error when I try to fetch only one page, but the error still exists for TwitterPager.

**Comment by geduldig** [comment]
TwitterPager does not support Premium yet. I'll make an update in the next few days. I'll check this error then too. Thx!

**Comment by geduldig** [comment]
Error 422 means there was a problem with your request. ([Error codes](https://developer.twitter.com/en/docs/basics/response-codes.html).) I can take a look if you post your request here.

Specifying start and end dates is possible. Use `fromDate` and `toDate`. ([Premium Search API](https://developer.twitter.com/en/docs/tweets/search/api-reference/premium-search).)

**Comment by peiyaoli2** [comment]
Hi - I was able to fix my request and the code works now. Thanks for your help!

**Comment by geduldig** [comment]
TwitterPager in the latest version (2.5.4) should work with with Premium Search now.
