### ISSUE TITLE
TwitterRequestError: Twitter request failed (403)

### ISSUE THREAD

**Issue by jchen812** [geduldig/TwitterAPI#105]
Hi,

I got approval of premium API from twitter yesterday and I set up the full archive sandbox dev environment. Now I am trying out the example code in premium search.py. But I got TwitterRequestError: Twitter request failed (403). I wonder where I got it wrong, could someone help? Thanks!

`SEARCH_TERM = 'pizza'
PRODUCT = 'fullarchive'
LABEL = 'label.json'

r = api.request('tweets/search/%s/:%s' % (PRODUCT, LABEL), 
                {'query':SEARCH_TERM})

for item in r:
    print(item['text'] if 'text' in item else item)`

**Comment by geduldig** [comment]
What is 'label.json'? Should be the name you gave your development environment. 
See https://developer.twitter.com/en/docs/tweets/search/api-reference/premium-search.
