### ISSUE TITLE
direct_message/event/new header

### ISSUE THREAD

**Issue by ccullin** [geduldig/TwitterAPI#106]
Hi,

I am updating my twitter applications to support the Account activity API and using your wrapper to send direct messages.  I get error 415 with all requests and I it worked a few days ago - either somethings has changed in my implementation or something has changed with the twitter endpoint.

Reading the twiiter docs the direct_message/evene/new.json has a new data object and requires a application/json header.  I believe the twitterAPI.request header is url_encode and when I send Direct Messages I get 415 response.  Code is below.

Does the twitterAPI support the new direct_message format described [here](https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/guides/direct-message-migration.html)

thanks.
Chris.

```
    twitterAPI = TwitterAPI(CONSUMER_KEY, CONSUMER_SECRET, ACCESS_KEY, ACCESS_SECRET)
    message = {
        "event": {
            "type": "message_create", 
            "message_create": {
                "target": {
                    "recipient_id": userID
                }, 
                "message_data": {
                    "text": messageText
                }
           }
       }
   }
    r = twitterAPI.request('direct_messages/events/new', json.dumps(message))
    log.debug("response code: {}".format(r.status_code))
```

**Comment by geduldig** [comment]
I just tried the endpoint myself, and it works fine. 415 is an odd error. You should try printing the message that goes with it to get more info. My guess is there is a problem with your keys and/or permissions. You could try generating another set of keys  and seeing if that resolves the error.

**Comment by ccullin** [comment]
Thanks for the quick reply.  Great API and glad to hear it is my end.

**Comment by do-n-khanh** [comment]
Hi geduldig, 

I got error u'{"errors":[{"code":32,"message":"Could not authenticate you."}]}'

I have tried:
r = api.request('statuses/update', {'status':'This is a tweet!'}) and it works, therefore, it can not be the problem of api = TwitterAPI(consumer_key, consumer_secret, access_token_key, access_token_secret)

My code is same with ccullin.

message = {
        "event": {
            "type": "message_create", 
            "message_create": {
                "target": {
                    "recipient_id": userID
                }, 
                "message_data": {
                    "text": messageText
                }
           }
       }
   }
    r = twitterAPI.request('direct_messages/events/new', json.dumps(message))

Do you have any suggestion?
Thanks

**Comment by geduldig** [comment]
In your app's permissions did you set the access to "Read, Write and Access direct messages"?

**Comment by do-n-khanh** [comment]
@geduldig: thanks. Yes. I had a look at the TwitterAPI.py file. It uses Request which is not support by Google App Engine. (I use Google App engine). 

Even though I try to use 
import requests_toolbelt.adapters.appengine
requests_toolbelt.adapters.appengine.monkeypatch()

I still get error:
 File "lib.zip/TwitterAPI/TwitterAPI.py", line 144, in request
    proxies=self.proxies)
  File "lib.zip/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "lib.zip/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "lib.zip/requests/adapters.py", line 412, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "lib.zip/requests/adapters.py", line 223, in cert_verify
    cert_loc = extract_zipped_paths(DEFAULT_CA_BUNDLE_PATH)
  File "lib.zip/requests/utils.py", line 249, in extract_zipped_paths
    tmp = tempfile.gettempdir()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/aa60bf86f0c4cd4e/python27/python27_dist/lib/python2.7/tempfile.py", line 45, in PlaceHolder
    raise NotImplementedError("Only tempfile.TemporaryFile is available for use")
NotImplementedError: Only tempfile.TemporaryFile is available for use

Can u please add Google App Engine Support to your API?
Thank you so much.

**Comment by geduldig** [comment]
You probably know more about google app engine than me. Why don't you add support as a pull request?

**Comment by do-n-khanh** [comment]
Could you please rewrite this part using "httplib" instead of "requests" library? 

with requests.Session() as session:
            session.auth = self.auth
            session.headers = {'User-Agent': USER_AGENT}
            method, subdomain = ENDPOINTS[endpoint]
            if method_override:
                method = method_override
            url = self._prepare_url(subdomain, resource)
            if 'stream' in subdomain:
                session.stream = True
                timeout = STREAMING_TIMEOUT
                # always use 'delimited' for efficient stream parsing
                if not params:
                    params = {}
                params['delimited'] = 'length'
                params['stall_warning'] = 'true'
            else:
                session.stream = False
                timeout = REST_TIMEOUT
            if method == 'POST':
                data = params
                params = None
            else:
                data = None
            try:
                r = session.request(
                    method,
                    url,
                    data=data,
                    params=params,
                    timeout=(CONNECTION_TIMEOUT,timeout),
                    files=files,
                    proxies=self.proxies)
                
            except (ConnectionError, ProtocolError, ReadTimeout, ReadTimeoutError,
                    SSLError, ssl.SSLError, socket.error) as e:
                raise TwitterConnectionError(e)
            return TwitterResponse(r, session.stream)

**Comment by geduldig** [comment]
Don't you think that is a lot to ask for?

**Comment by do-n-khanh** [comment]
hi,

sorry. please ignore it. i manage to make tweepy work with new Direct Message Api.
