### ISSUE TITLE
TwitterPager fails with /followers/ids endpoint (and others)

### ISSUE THREAD

**Issue by sauoq** [geduldig/TwitterAPI#107]
I believe the failure can occur with any results that don't include an 'id' key in the returned json. 

The problem is that the new cursor value isn't added to params. This is due to the following code in TwitterPager.py: 

                if id is None:
                    continue

                # use either id or cursor to get a new page
                if cursor != -1:
                    self.params[cursor_param] = cursor
                elif new_tweets:
                    self.params['since_id'] = str(id)
                else:
                    self.params['max_id'] = str(id - 1)
As you can see, when id is None, self.params[cursor_param] will not be set. In my local copy, I have removed that initial if statement and changed the follow if/elif/else to the following: 

                # use either id or cursor to get a new page
                if cursor != -1:
                    self.params[cursor_param] = cursor
                elif new_tweets and id is not None:
                    self.params['since_id'] = str(id)
                elif id is not None:
                    self.params['max_id'] = str(id - 1)
                else:
                    continue

So far this is working for my purposes, however my testing has been limited. YMMV, so I'm offering this description of the problem and potential fix here rather than as a pull request. 

Cheers,
sauoq

**Comment by geduldig** [comment]
I had to make an additional change to what you suggested. You may want to re-test. 
Thanks!
