### ISSUE TITLE
account activity api subscription failed.

### ISSUE THREAD

**Issue by yandenghong** [geduldig/TwitterAPI#109]
when i use:   twitter_api.request('account_activity/all/:development/subscriptions', {'webhook_id':xxxx}), it should have sent a POST request, but only sent a GET request, which caused me to be unable to subscribe to my webhook.

**Comment by yandenghong** [comment]
twitter_api.request('account_activity/all/subscriptions/count')  is not supported

**Comment by geduldig** [comment]
For your first issue, try
`twitter_api.request('account_activity/all/:development/subscriptions', {'webhook_id':xxxx, method_override:'POST'})`

For your second, I'll add that endpoint soon.

**Comment by yandenghong** [comment]
I am very sorry that I did not use this method correctly. According to your instructions, it worked, thanks.
