### ISSUE TITLE
Enhancement - Add Proxy Support

### ISSUE THREAD

**Issue by RudeDog69** [geduldig/TwitterAPI#11]
Thanks for all the work  you put into this.  One thing that I see that could help is adding proxy support.  I see it uses requests, but for the life of me I can not figure out how to add that function in the script, it looks like the base code would need to be changed to allow for it.

This is such a simple and easy to use script for the API, thanks for getting the OAuth right!
Rudy

**Comment by weaming** [comment]
show also add http proxy too, http://docs.python-requests.org/en/master/user/advanced/#proxies

**Comment by geduldig** [comment]
In version 2.5.1, added syntax for http and https proxies as suggested.
