### ISSUE TITLE
iterator fails

### ISSUE THREAD

**Issue by vefae** [geduldig/TwitterAPI#110]
Hi, while I try to run my code, I get the page iterator error. I could not find any solutions to the problem and the same code was working a couple of weeks ago. I do not know if it is a bug or a problem caused my me. If you can have a look at the iterator if it works, that would be great. 
I am using Premium Search 30 Days API

**Update: After analyzing the previous issues, I realized that it must be something related to my search params, which were:**
`pager = TwitterPager(api, 'tweets/search/30day/:30da', {'query': SEARCH_TERM, 'lang':LANG, 'fromDate':"201809180000",'toDate':'201809200000'}).get_iterator(wait=6,new_tweets=True)`

Then I removed the LANG, eventhough it exists in the Premium Search API parameters, the code brought back only the first page of the results. Then it gave the same error as below. 

My question, is it not possible to add Lang parameter to the query?

Traceback (most recent call last):
  File "amazon.py", line 33, in <module>
    for item in pager:
  File "/home/vefa/.local/lib/python3.6/site-packages/TwitterAPI/TwitterPager.py", line 47, in get_iterator
    it = r.get_iterator()
  File "/home/vefa/.local/lib/python3.6/site-packages/TwitterAPI/TwitterAPI.py", line 193, in get_iterator
    raise TwitterRequestError(self.response.status_code)
TwitterAPI.TwitterError.TwitterRequestError: Twitter request failed (422)

**Comment by geduldig** [comment]
'lang' is available in Standard Search but not in Premium Search. Check out the docs here:
https://developer.twitter.com/en/docs/tweets/search/api-reference/premium-search
