### ISSUE TITLE
result_type parameter premium/enterprise search

### ISSUE THREAD

**Issue by BoPengGit** [geduldig/TwitterAPI#111]
Hi,

For standard search, I see a search parameter "result_type" that has the options: mixed, recent, popular. For premium/enterprise search do you guys know if there is a similar parameter to sort the tweet results?

Thanks!

**Comment by geduldig** [comment]
No, that does not exist in Premium Search.
[API doc](https://developer.twitter.com/en/docs/tweets/search/api-reference/premium-search.html#DataEndpoint)
