### ISSUE TITLE
DM Delete missing

### ISSUE THREAD

**Issue by AgoraSecurity** [geduldig/TwitterAPI#112]
In https://github.com/geduldig/TwitterAPI/blob/master/TwitterAPI/constants.py
There´s no function for deleting a DM (DELETE direct_messages/events/destroy)

Twitter API:
https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/delete-message-event

**Comment by AgoraSecurity** [comment]
Note, I´m trying to find a way to read the DM, do some action and then ignore the DM.

I used to use
GET direct_messages with since_id
https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/get-messages

Anyhow that option is no longer available.
What I thought was reading the DM / then deleting it (not ideal, but the only way I could think that didn't involve iterating through each DM).

If someone has any better ideas (than deleting) that would be awesome!

**Comment by geduldig** [comment]
I will add the DM delete to the constants.py. I don't understand your second post with the question.

**Comment by geduldig** [comment]
Done
