### ISSUE TITLE
Twitter Premium API Sandbox : Error Code 403

### ISSUE THREAD

**Issue by pj1114** [geduldig/TwitterAPI#113]
Hi, I am trying to grab data from Twitter through Premium API Sandbox.

I have built the 30-day Premium API Sandbox and the following is my code to send the request.

-------------------------------------------------------------------------------------------
```
from TwitterAPI import TwitterAPI

consumer_key = 'XXX'
consumer_secret = 'XXX'
access_token = 'XXX'
access_token_secret = 'XXX'

api = TwitterAPI(consumer_key, consumer_secret, access_token, access_token_secret)
r = api.request('tweets/search/30day/:test.json', {'q' : 'python') //test is my own label

for item in r:
     print(item['text'])
```
-------------------------------------------------------------------------------------------

However, I keep receiving error code 403 like :

-------------------------------------------------------------------------------------------
```
Traceback (most recent call last):
  File "Twitter_api_srch_full.py", line 11, in <module>
    for item in r:
  File "/anaconda3/lib/python3.6/site-packages/TwitterAPI/TwitterAPI.py", line 206, in __iter__
    return self.get_iterator()
  File "/anaconda3/lib/python3.6/site-packages/TwitterAPI/TwitterAPI.py", line 193, in get_iterator
    raise TwitterRequestError(self.response.status_code)
TwitterAPI.TwitterError.TwitterRequestError: Twitter request failed (403)
```
-------------------------------------------------------------------------------------------

Do you know any potential reasons to cause such error?

Thank you for your helping :)

**Comment by geduldig** [comment]
The problem is you are using "q" as a parameter name. I have a small example here with the correct parameter: 
https://github.com/geduldig/TwitterAPI/blob/master/examples/premium_search.py

If you want to learn about all the acceptable parameters check out the docs on Twitter's developer site:
https://developer.twitter.com/en/docs/api-reference-index
