### ISSUE TITLE
account_activity api examples

### ISSUE THREAD

**Issue by kercos** [geduldig/TwitterAPI#114]
Hi,

Is it possible to see some example on the use of account_activity api (via webhooks)?

I've managed to register a webhook with the following:
```
def set_webhook():    
    r = api.request(
        'account_activity/all/:{}/webhooks'.format(key.TWITTER_ENVNAME), 
        {'url': 'https://my.doimain.com/twitter'},
        method_override='POST'
    )
    return r.text
```
and get the webook info with the following:
```
def get_webhook_info():
    r = api.request(
        'account_activity/all/:{}/webhooks'.format(key.TWITTER_ENVNAME), 
        method_override='GET'
    )
    return r.text
```

But for instance can't trigger CRC_request with the following:
```
def trigger_CRC_request():
    r = api.request(
        'account_activity/all/:{}/webhooks'.format(key.TWITTER_ENVNAME), 
        method_override='PUT'
    )
    return r.text
```

Thanks

**Comment by geduldig** [comment]
Do you get an error back?

**Comment by geduldig** [comment]
I think that error message is correct. I don't see this endpoint in the Twitter docs:
https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/api-reference/aaa-premium

I think it should bet POST instead of PUT.

**Comment by kercos** [comment]
you are right it should have been:
`account_activity/all/:env_name/webhooks/:webhook_id`

**Comment by kercos** [comment]
What about this?

```
def add_user_subscription():
    r = api.request(
        'account_activity/all/:{}/subscriptions'.format(key.TWITTER_ENVNAME), 
        method_override='POST'
    )
    return r.text
```

it returns:
`{"errors":[{"code":348,"message":"Client application is not permitted to access this user\'s webhook subscriptions."}]}`

**Comment by geduldig** [comment]
The fix at the end of this thread may apply to you.
https://twittercommunity.com/t/getting-error-code-348-while-trying-to-add-subscription/101796/8

**Comment by kercos** [comment]
Thanks a lot!
You saved my day 😄

**Comment by geduldig** [comment]
De nada.
