### ISSUE TITLE
Question: Premium tier API Usage Parameter

### ISSUE THREAD

**Issue by BoPengGit** [geduldig/TwitterAPI#115]
Hi,

I have a question. I see here: https://developer.twitter.com/en/docs/developer-utilities/usage-api/overview there is an endpoint to query to see account usage for enterprise accounts. I was wondering for premium tier, does anyone know if there is an endpoint that I can use to see how much usage I have remaining for the month?

Thank you.

**Comment by geduldig** [comment]
I think the answer is no. You can see usage on your dashboard here:
https://developer.twitter.com/en/dashboard
