### ISSUE TITLE
TwitterPager doesn't stop after retrieving all tweets

### ISSUE THREAD

**Issue by kst83** [geduldig/TwitterAPI#117]
I'm using the TwitterPagerlike this:

    ```
    pager = TwitterPager(api, 'statuses/user_timeline',
                             {'screen_name': 'wuv', 'count': 200, 'trim_user': 'true', 'include_rts': 'true',
                              'tweet_mode': 'extended'})
    for item in pager.get_iterator(wait=5, new_tweets=True)
```
For some reason it doesn't stop after loading the newest message. Is this a bug or is something wrong with my code?

**Comment by geduldig** [comment]
I'm not sure if I quite understand by "it doesn't stop after loading the newest message."

When you specify "new_tweets=True" the iterator will return results forever, pausing when there are no 
matching tweets and continuing when there are. 

When you specify "new_tweets=False" the iterator will return only prior results. Results are in reverse chronological order and stop when some limit reached. Twitter limits how far in the past or how many results you may access depending upon the type of request.

**Comment by kst83** [comment]
so new_tweets=true is meant to stream new tweets?
How do you limit the results returned with new_tweets=false by time? E.g. just getting tweets starting from yesterday?

**Comment by geduldig** [comment]
Yes, that's right about `new_tweets`. To limit by date you have two options.

One is to consult the API docs to see if there is a parameter for date ranges. In the case of user timelines there are no such parameters. Here is the doc: https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline.html

The other is to check the value `created_at` for each tweet returned. When you reached the end of the date range you are interested in, simply break out of the loop.

**Comment by kst83** [comment]
Thanks for the input, this helps!
