### ISSUE TITLE
ImportError: No module named requests_oauthlib

### ISSUE THREAD

**Issue by arikuja** [geduldig/TwitterAPI#12]
I get the following error when trying to import TwitterAPI:

ImportError: No module named requests_oauthlib

**Comment by PiEatinNerd** [comment]
I had the same issue, this fixed it:

sudo pip3 install twython --upgrade

**Comment by geduldig** [comment]
LOL twython != TwitterAPI

`sudo pip3 install TwitterAPI --upgrade`
