### ISSUE TITLE
TwitterPager Premium Search gives 422

### ISSUE THREAD

**Issue by connorwaslo** [geduldig/TwitterAPI#120]
Hello,

I'm trying to use the TwitterPager to get historical tweets, and keep getting a 422 response. Here's my code, any point in the right direction would be awesome.

```
every_tweet = TwitterPager(api, 'tweets/search/fullarchive/:dev', {'q': search, 'since': since, 'until': until, 'tweet_mode': 'extended'})

for tweet in every_tweet.get_iterator(): # Do my thing
```

This doesn't seem very far off from the examples given for premium search or for TwitterPager, where am I going wrong?

**Comment by geduldig** [comment]
Hi -
Premium search uses different parameter names. The parameter names you have only work with the standard search. It's explained here: https://developer.twitter.com/en/docs/tweets/search/api-reference/premium-search.html

**Comment by geduldig** [comment]
Can you post a minimal but complete example that produces the 422 error?

**Comment by connorwaslo** [comment]
I have a Full Environment / Premium dev environment label called "dev." The endpoint works just fine, when I change that I get a different error, but this example should recreate it:

```
from TwitterAPI import TwitterAPI, TwitterPager
import json

# Get all credentials
file = 'creds/connor_twitter.json'

with open(file, 'r') as file:
    creds = json.load(file)

api = TwitterAPI(creds['CONSUMER_KEY'], creds['CONSUMER_SECRET'],
                 creds['ACCESS_TOKEN'], creds['ACCESS_SECRET'])

every_tweet = TwitterPager(api, 'tweets/search/fullarchive/:dev',
                           {'query': '#puppies', 'fromDate': '2018-09-13', 'toDate': '2018-09-14'})

for tweet in every_tweet.get_iterator():
    print(tweet)
```

**Comment by geduldig** [comment]
The date format looks incorrect. Try this instead:
```python
every_tweet = TwitterPager(api, 'tweets/search/fullarchive/:dev',
                           {'query': '#puppies', 'fromDate': '201809130000', 'toDate': '201809140000'})
```

**Comment by connorwaslo** [comment]
Fantastic! Thank you this works!

What about using the 'maxResults' parameter? Adding the following parameter:

`'maxResults': 500`

again causes a 422 error.
