### ISSUE TITLE
"lang" operator does not seem to wirk with premium API

### ISSUE THREAD

**Issue by simonsax** [geduldig/TwitterAPI#124]
My app is able to query the premium api but as soon as I add the lang-operator, I get an 422 error.

This code is working:
`tweets = TwitterPager(api,'tweets/search/30day/:full1', {'query': '@UPC_Switzerland'})`

As soon as I add the lang-operator, I get an error (TwitterAPI.TwitterError.TwitterRequestError: Twitter request failed (422)):
`tweets = TwitterPager(api,'tweets/search/30day/:full1', {'query': '@UPC_Switzerland', 'lang': 'en'})`

Where is my problem? According to the documentation lang should be a valid operator.
Thank you for looking into this.

**Comment by geduldig** [comment]
You probably are reading the documentation for the standard search `search/tweets`. 
Instead, read this https://developer.twitter.com/en/docs/tweets/search/api-reference/premium-search.html
