### ISSUE TITLE
Extended Tweets with premium api

### ISSUE THREAD

**Issue by NikDude59** [geduldig/TwitterAPI#125]
Currently using the following code but keep getting the 422 error. Is it possible to use 'tweet_mode'='extended' with premium api?

This is my code?

`r = api.request('tweets/search/%s/:%s' % (PRODUCT, LABEL),
                {'query': SEARCH_TERM,  'tweet_mode':'extended',  'fromDate':'201801010000', 'toDate':'201901010000', 'maxResults':'500' })
for item in r:
   print(item['created_at'])
   print(item['full_text'])`

Sorry for the formatting but each line is as it should be it's just the tweet mode i need to address I think

If it cannot be resolved, is there a workaround?

**Comment by geduldig** [comment]
Here is the Premium Search doc page: https://developer.twitter.com/en/docs/tweets/search/api-reference/premium-search.html
Looks like the answer is no `tweet_mode`.

But, in this doc is your answer: https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/intro-to-tweet-json

If the the tweet is extended, it will contain `item['extended_tweet']['full_text']`.

**Comment by NikDude59** [comment]
So i removed the tweet_mode from above and now this reads:

`for item in r:
   print(item['created_at'])
   print(item['text'])
   print(item['extended_tweet']['full_text'])`

But i get KeyError:'extended_tweet'

**Comment by geduldig** [comment]
The operative words are "if the tweet is extended..." Don't assume the tweet is extended. Test first:
```python
if 'extended_tweet' in item: 
  print(item['extended_tweet']['full_text'])
else if 'text' in item:
  print(item['text'])
```

**Comment by NikDude59** [comment]
```
`if 'extended_tweet' in item: 
  print(item['extended_tweet']['full_text'])
else:
  print(item['text'])`
```

Thank you so much. This is the code the worked for me

**Comment by tbakare** [comment]
`for tweet in tweetss:`
`     if hasattr(tweet, 'extended_tweet'):`
`        print(tweet.extended_tweet['full_text'])`
`    else:`
`        print(tweet.text)`

This worked partially for me. Some tweets still got truncated though because not all tweets that were extended had the extended_tweet attribute.

**Comment by geduldig** [comment]
Example?
