### ISSUE TITLE
Feature Request: sleep when rate limited

### ISSUE THREAD

**Issue by brad-safetonet** [geduldig/TwitterAPI#126]
I'm using the TwitterPager to page through a large number of tweets. I'd like to be able to just sleep when error 429 is encountered and then continue on with the pages of tweets after more quota is available. Right now, if 429 is thrown, the iterator seems to die, so I can't keep using it. If I re-create the iterator, then I think that it would just start at the beginning again and re-retrieve duplicate tweets.

Does this make sense? Or is there something I'm doing wrong with the way I'm using the API?

**Comment by geduldig** [comment]
`TwitterPager.get_iterator` takes a `wait` parameter. This is the number of seconds to wait before making a new request. Default is 5 seconds. http://geduldig.github.io/TwitterAPI/twitterpager.html
Depending on the rate limit for the type of request you are making, you can set a longer wait interval. Add a little extra to be conservative.

**Comment by brad-safetonet** [comment]
I'll try that strategy. I've set my program to wait 6 seconds between calls. I'll be keeping an eye on it to see if it stays up reliably over the next day or so.

**Comment by geduldig** [comment]
Also, I assume you are using Standard Search request `search/tweets`. If you are not already doing so, you are better off using OAuth2 application authentication. This will up your rate limit to 450 requests per 15 minutes, which translates into a 2 second wait. Or, conservatively, `wait=2.5`.
