### ISSUE TITLE
Truncated retweets with premium api

### ISSUE THREAD

**Issue by caimeng2** [geduldig/TwitterAPI#127]
Hi,

Is it possible to get untruncated retweets with this package? My code is as follows.

    r = api.request('tweets/search/%s/:%s' % (PRODUCT, LABEL), 
                    {'query':SEARCH_TERM, 
                     'fromDate':'',
                     'toDate':''
                     })

    csvFile = open('result.csv','a')
    csvWriter = csv.writer(csvFile)
    counter = 0

    for item in r:
        if 'extended_tweet' in item: 
            csvWriter.writerow([item['created_at'],item['user']['screen_name'], item['extended_tweet']['full_text'] if 'full_text' in item else item])
        else:
            csvWriter.writerow([item['created_at'],item['user']['screen_name'], item['text'] if 'text' in item else item])
        counter = counter + 1
        if (counter == 100):
            break

    csvFile.close()

**Comment by geduldig** [comment]
See this issue https://github.com/geduldig/TwitterAPI/issues/125

The answer is that Premium search does not return `extended_tweet`. It only exists for Standard Search.

**Comment by caimeng2** [comment]
Oh bummer. So there is no workaround to get untruncated retweets with premium search, right?

**Comment by geduldig** [comment]
You will get them with Premium search. The tweet will contain either `text` for a truncated tweet or `full_text` for an extended tweet. You must check which one is present in the tweet.

**Comment by caimeng2** [comment]
Thank you very much for your response. I just learned that a long retweet will always be truncated no matter extended or not. The key is to check "retweeted_status" and then see the original message. 
Appreciate your awesome work =)
