### ISSUE TITLE
Error message __main__ is not a package

### ISSUE THREAD

**Issue by gspags** [geduldig/TwitterAPI#128]
Hi! I am new to coding (I have previously worked with R, but have never used Python). I am working on research project that requires collecting Tweets that fit our search criteria and running them through a basic analysis. I have obtained a Twitter developer account and generated my API keys and access tokens, but I am still having difficulty getting the code to run. I tried running the TwitterAPI.py program and input my API keys and access tokens in ' ' every time I saw them in the code (now I'm thinking I may just have needed to enter them once in the first few lines of the code to define the variables). However, the error messages that I'm getting when I try to run the TwitterAPI.py program is that "__main__ is not a package". I feel like this is probably a super basic problem, but since I'm new to Python, I've been stuck here for a little while and am having trouble figuring it out. I would appreciate your help!!

**Comment by geduldig** [comment]
TwitterAPI.py is not a standalone program. Typically, you would write a program that calls TwitterAPI.py to use its methods. For examples of standalone programs that use TwitterAPI.py, look here:

https://github.com/geduldig/TwitterAPI/tree/master/examples

You will need to enter your credentials into whichever example program you want to use.

**Comment by gspags** [comment]
Ok so for example, if I wanted to search Tweets, how would I use an example program (such as search_tweets.py) and the TwitterAPI.py program? What would be the appropriate way to enter the commands into the File Editor of IDLE? I apologize for being so coding illiterate, but I really want to figure this out for my project!

**Comment by geduldig** [comment]
You don't have to enter any commands into an editor. All you would need to enter are your credentials into search_tweets.py from your editor. But, your question leads me to ask, have you ever run a python program? Also, have you ever installed a third-party python library with `pip` to use with your python program? I think these would both be prerequisite tasks in order to start using TwitterAPI in your programs.

**Comment by gspags** [comment]
No I have not! I saw a lot of references to pip but I wasn't sure what exactly it is. I'm not sure if you're familiar with R, but is it the same as installing a library there?

**Comment by geduldig** [comment]
All this is pretty well explained on the web. This page is a pretty place to start 
https://wiki.python.org/moin/BeginnersGuide

I would also suggest reading the front page of the TwitterAPI distribution. If you have programmed in R, you should be able to quickly get up to speed with Python.
