### ISSUE TITLE
Not sure where to ask this and can’t figure it out. How to test login w/o sending tweet?

### ISSUE THREAD

**Issue by mwoolweaver** [geduldig/TwitterAPI#130]
I have been searching for the way to validate credentials using TwitterAPI and I can’t figure it out for life of me. So I was wondering if you could help me out? 

How to test login w/o sending tweet?

**Comment by geduldig** [comment]
You would make a request for `account/verify_credentials`. It will return account information documented at https://developer.twitter.com/en/docs/accounts-and-users/manage-account-settings/api-reference/get-account-verify_credentials.

However, I don't think it will tell you if your credentials will allow you to tweet

**Comment by mwoolweaver** [comment]
So this 

`
r = api.request('account/verify_credentials')
`

And then parse `r` as json?

**Comment by geduldig** [comment]
That's right. The returned value `r` will be a JSON structure as outlined in the sited doc.

**Comment by mwoolweaver** [comment]
Thank you for your help!! Would’ve been a while before I got that on my own.
