### ISSUE TITLE
AND operator in Twitter API Premium

### ISSUE THREAD

**Issue by ardiantovn** [geduldig/TwitterAPI#135]
I tried two queries using Twitter fullarchive Premium API sandbox version:
1. `'corona OR masker'`
2. `'corona AND masker'`
Query number 2 returns error 422. Why only query number 1 is successful? How to use the `AND` operator correctly?
Thank You

**Comment by geduldig** [comment]
`AND` is not an operator. For number 2, do this instead: `'corona masker'`.

**Comment by ardiantovn** [comment]
Ok. I want to get tweets containing the word `corona` and `masker`. How to write this query correctly?

**Comment by geduldig** [comment]
Do this: `'corona masker'`.

**Comment by ardiantovn** [comment]
I'm sorry, I didn't pay attention to your answer before. I am sorry...

I want to ask another similar thing, for example I want to get a tweet about Corona. I want to make sure that the tweet contains these words: (mask, hand sanitizer, or donation).

I can get the results I expect at www.twitter.com/search by writing like this:
`corona AND (mask OR "hand sanitizer" OR donation)`.

I can't write a query like that on the Twitter API because `AND` is not an operator.
Then, do I have to write on the Twitter API like this to get the results I want?
`corona mask "hand sanitizer" donation`

Thank you

**Comment by geduldig** [comment]
`corona (masker OR "hand sanitizer" OR donation`

**Comment by ardiantovn** [comment]
Thank you very much for the answer...

**Comment by geduldig** [comment]
You are welcome!
