### ISSUE TITLE
Results to csv

### ISSUE THREAD

**Issue by kimmyeonggyu** [geduldig/TwitterAPI#137]
I used premium API and codes below:

1st question: 
#(1) worked (data in csv file) but #(2) didn't work (no data in csv file).
What makes the difference?
I need all items in #(2)

2nd question:
Final csv file had a blank line after each collected tweet. How can I delete a blank line. 

----------------------------------------------------------------------
import csv
csvFile=open('results.csv','w', encoding='utf-8')
csvWriter=csv.writer(csvFile)

consumer_key = "xxx"
consumer_secret = "xxx"
access_token = "xxx"
access_token_secret = "xxx"

from TwitterAPI import TwitterAPI
api = TwitterAPI(consumer_key, consumer_secret, access_token, access_token_secret)

SEARCH_TERM = 'SEARCH_TERM'
PRODUCT = 'fullarchive'
LABEL = 'production'

##################################(1) WORKING
for item in pager.get_iterator():
 if 'extended_tweet' in item: 
  csvWriter.writerow([item['created_at'],item['extended_tweet']['full_text']])
 else:
  csvWriter.writerow([item['created_at'],item['text']])

##################################(2) NOT WORKING
for item in pager.get_iterator():
 if 'extended_tweet' in item: 
  csvWriter.writerow([item['id_str'], item['created_at'], item['user']['id'], item['user']['screen_name'], item['user']['followers_count'], item['retweet_count'], item['favorite_count'], item['extended_tweet']['full_text'], item['user']['location']])
 else:
  csvWriter.writerow([item['id_str'], item['created_at'], item['user']['id'], item['user']['screen_name'], item['user']['followers_count'], item['retweet_count'], item['favorite_count'], item['text'], item['user']['location']])

**Comment by geduldig** [comment]
#1 You need to print the error to find out.
#2 Blank line is created by  `csvWrite.writerow`. I am not familar with this.

**Comment by kimmyeonggyu** [comment]
How to print error? 
I think it's not an error of TwitterAPI.
When I print each item in python, it displays the results. 
It seems like an error of writing on csv file.

**Comment by kimmyeonggyu** [comment]
Is there any other code that I can output the results as .txt or .csv file??

**Comment by geduldig** [comment]
Your questions are not related to TwitterAPI. You would do best to post them on a forum such as stackoverflow.com.

**Comment by kimmyeonggyu** [comment]
Thank you.
