### ISSUE TITLE
Query build and output

### ISSUE THREAD

**Issue by BLT81** [geduldig/TwitterAPI#138]
I have two related questions / issues:
Will this package handle more complex queries? I'm having difficulty getting to search using operators such as "has:media" and "-RT". Related to that, how can I get it to output the search term that it sends to Twitter? This would be useful in troubleshooting the first problem I'm having.

**Comment by geduldig** [comment]
I assume you are using Premium Search. Then your request should look something like this: 
```python
r = api.request('tweets/search/%s/:%s' % (PRODUCT, LABEL), {'query':'pizza -RT has:media'})
```

I'm not excactly sure what your second question is. What do you want to output your search term? Do you want TwitterAPI to save your `query` string for you?

**Comment by BLT81** [comment]
Yes, I'm using premium. The second part is just to see how the package assembles the query because it seems like some operators are used outside of 'query' like dates or could they all be used as values of 'query'?

**Comment by BLT81** [comment]
Thank you! This package is great!
