### ISSUE TITLE
Premium search API full archive: ERROR 422

### ISSUE THREAD

**Issue by wanitchayap** [geduldig/TwitterAPI#139]
Hi @geduldig ! 

I use a premium search API with the full archive product. This is my code:
```
r = TwitterPager(api, 'tweets/search/fullarchive/:dev',
                 {'query': '$AAPL OR $IBM OR $CDNS lang:en -is:retweet',
                 'fromDate': '201812310000',
                 'toDate': '201901062359',
                 'maxResults':500})
lst = []
for item in r.get_iterator(wait=2):
    lst.append(item)
```
The length of my query is under 1024 characters. I am not really sure why I get the 422 error. Could you help me please?

Thank you!

**Comment by andypiper** [comment]
Are you using the free sandbox version? I don't think the `is:retweet` operator is available in the sandbox version.

**Comment by wanitchayap** [comment]
@andypiper No, I don't use the free sandbox version. I directly use the paid premium version.

**Comment by geduldig** [comment]
I don't have access to the paid version. So, I can only test with the sandbox. In addition to `is:retweet` (as @andypiper  said), the sandbox version is limited to `'maxResult':100` and appears to not have access to stock symbols such as `$IBM` either.

For grins, I suggest trying to make your search compatible with running in a sandbox. If that works, there may be something wrong with your access to the paid version. Just a guess.

**Comment by andypiper** [comment]
I agree that those would be my next debug steps as well. Definitely happy to help here if this is an identifiable issue, but let’s narrow the parameters and work from there :-)

**Comment by wanitchayap** [comment]
@geduldig and @andypiper . Thank you so much for your helps!

I have tried this on the sandbox environment:
```
r = TwitterPager(api, 'tweets/search/30day/:sanddev',
                 {'query': 'AAPL OR IBM OR CDNS lang:en',
                     'fromDate': FROM_DATE,
                     'toDate': TO_DATE,
                     'maxResults':100})
lst = []
for item in r.get_iterator(wait=2):
    lst.append(item)
```
This works fine for me!

Please correct me if I am wrong: Once I switch to premium environment, I should be able to add `-is:retweet` to my query and `'maxResult':500`...?

Then was my original problem stemmed from using the `$` symbol in the query? Can I use `$` in the premium environment or not?

**Comment by geduldig** [comment]
Unfortunately, I don't have access to the premium paid environment. So, if you don't mind, the next thing to confirm is that you can access paid premium for the simplist case, which may answer your question about `$` symbols. Let's see if the following wors for you:
```python
r = TwitterPager(api, 'tweets/search/fullarchive/:dev', {'query': 'IBM'})
```

**Comment by wanitchayap** [comment]
@geduldig 

I can run this successfully:
```
r = TwitterPager(api, 'tweets/search/fullarchive/:dev', {'query': 'IBM'})
```
as well as 
```
r = TwitterPager(api, 'tweets/search/fullarchive/:dev', {'query': 'IBM OR AAPL lang:en -is:retweet',
                     'fromDate': FROM_DATE,
                     'toDate': TO_DATE,
                     'maxResults':500})
```

**Comment by geduldig** [comment]
The supported search operators are listed here: https://developer.twitter.com/en/docs/tweets/search/overview/premium#AvailableOperators. It appears `$` is not supported, which you have also confirmed to be the case.
