### ISSUE TITLE
Addind endpoints that are now out of labs

### ISSUE THREAD

**Issue by smushis** [geduldig/TwitterAPI#145]
I was searching for getting tweet by their ID and I found those [Endpoints](https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference). And in your file constants.py, you have those functions in labs section. 
Are you planning to add those endpoints to a normal usage (without needing to sub to labs) ?

**Comment by geduldig** [comment]
Yes, I will be adding the new endpoints within the next couple of weeks. You want, you can add them yourself to your local installation.

**Comment by smushis** [comment]
Ok, thanks!

**Comment by geduldig** [comment]
I'm closing this issue. Use https://github.com/geduldig/TwitterAPI/issues/146 instead.
