### ISSUE TITLE
Twitter v2 Support?

### ISSUE THREAD

**Issue by dylancaponi** [geduldig/TwitterAPI#146]
@geduldig Do you plan to support Twitter v2 API or would you accept PRs?

https://developer.twitter.com/en/docs/twitter-api/early-access

**Comment by geduldig** [comment]
Pull requests are gladly welcomed!

**Comment by dylancaponi** [comment]
I noticed `VERSION` is hardcoded [here](https://github.com/geduldig/TwitterAPI/blob/master/TwitterAPI/constants.py#L20)
Would you prefer that I override that in `_prepare_url` when the endpoint contains `2/` eg `'2/users/by/username/:PARAM'` or by some other method?

**Comment by geduldig** [comment]
Probably not include the version the way you have it. I'm just starting to think about this...

I'd like to offer the option of using either V1.1 or V2 but not both simulaneously. So, thinking of making these changes:

1) Add an optional parameter to the `request` method called `version`. Default will be `None`. Set `self.version = version`.
2) Modify `'_prepare_url` to use `self.version` only if it is not `None`.

I also need to read more of the V2 docs to see if it will require changes to `_RestIterable` and `_StreamingIterable` classes and to `TwitterPagerl.py`.

**Comment by dylancaponi** [comment]
Thanks! I'll open a WIP PR tonight.

**Comment by geduldig** [comment]
See https://github.com/geduldig/TwitterAPI/pull/147

**Comment by geduldig** [comment]
v2.6 now supports v2 API
several new v2 examples uploaded
