### ISSUE TITLE
Specifying user location

### ISSUE THREAD

**Issue by ZahraBader** [geduldig/TwitterAPI#148]
Hi dear 
Can I specify the user location in my query ? 
r2 = TwitterPager(api, 'tweets/search/%s/:%s' % (PRODUCT, LABEL),
        {'query':SEARCH_TERM, 
        'fromDate':'201910010000',
        'toDate':'201912032359',
        "maxResults":500
        }).get_iterator(wait=2)

**Comment by geduldig** [comment]
Yes. It is documented here: https://developer.twitter.com/en/docs/twitter-api/v1/tweets/search/overview/premium#AvailableOperators
Read the section on Geospatial Operators.

**Comment by andypiper** [comment]
It is worth being aware that only a very small percentage of Tweets have user geodata assigned, so if you see a small result set, that is likely to be the case.
