### ISSUE TITLE
search tweets but exclude retweets

### ISSUE THREAD

**Issue by YingjieLiScience** [geduldig/TwitterAPI#149]
how to add such a parameter to the search? Thanks!

**Comment by dbrennand** [comment]
Hi @YingjieLiScience 

I believe you need to use some of the standard operators when performing the search query.

See https://developer.twitter.com/en/docs/twitter-api/v1/tweets/search/guides/standard-operators

The example probably most useful to you would be:
![image](https://user-images.githubusercontent.com/52419383/95319586-9f3b4180-0887-11eb-9617-b974fcc2cf97.png)

Hope this helps 😃

**Comment by YingjieLiScience** [comment]
This is great! Thanks, @dbrennand !!!

**Comment by willmendil** [comment]
I'm following up this question, I had already found the standard operators page, but I don't understand how to combine this with a search

```python
r = api.request({'search/tweets': {'q':'puppy', 'count': 20}, "statuses/filter": "retweets"})
```

does not work
