### ISSUE TITLE
Using api.request with search tweets but exclude retweets

### ISSUE THREAD

**Issue by willmendil** [geduldig/TwitterAPI#150]
I am posting a new issue as to get an opened ticket. This is a follow up to #149 

I'm following up this question, I had already found the standard operators page, but I don't understand how to combine this with a search

```python
r = api.request({'search/tweets': {'q':'puppy', 'count': 20}, "statuses/filter": "retweets"})
```

does not work

**Comment by dbrennand** [comment]
Hi @willmendil 

You got the right idea however, there are some syntax errors in your example. 

`search/tweets` and `statuses/filter` are to separate API endpoints. What you’re looking for is to combine either one of those endpoints with the second parameter for the `request` method which is **params**. This parameter takes a dictionary so you were on the right lines there 👍🏻

I will give a nice example. Say I want to use the search endpoint to get all of Donald Trumps latest 10 tweets which are not retweets. I would do the following:

```
# Assuming you have already authenticated above
api = api.request(“search/tweets”, {“q”: “from:realdonaldtrump -filter:retweets”, “count”: “10”, “result_type”: “recent”})

# Interact with Tweets here
```

Hope this helps! 👍🏻

**Comment by willmendil** [comment]
Ok, got it, works great, thanks !
