### ISSUE TITLE
How to stream a query with expansion tweet using TwitterAPI V2?

### ISSUE THREAD

**Issue by ardiantovn** [geduldig/TwitterAPI#154]
I want to stream a query and get tweet.fields and user.fields in the result. This is the code I used:

```
from TwitterAPI import TwitterAPI, TwitterOAuth, TwitterRequestError, TwitterConnectionError

QUERY = '"pizza" OR "burger"'
EXPANSIONS = 'entities.mentions.username'
TWEET_FIELDS='author_id,conversation_id,created_at,entities,geo,id,lang,public_metrics,source,text'
USER_FIELDS='created_at,description,entities,location,name,profile_image_url,public_metrics,url,username'
try:
	consumer_key="xxx"
	consumer_secret="xxx"
	api = TwitterAPI(consumer_key, consumer_secret, auth_type='oAuth2', api_version='2')

	# ADD STREAM RULES
	r = api.request('tweets/search/stream', {'add': [{'value':QUERY}]})

	print(f'[{r.status_code}] RULE ADDED: {r.text}')
	if r.status_code != 201: exit()

	# GET STREAM RULES
	r = api.request('tweets/search/stream/rules', method_override='GET')
	print(f'[{r.status_code}] RULES: {r.text}')
	if r.status_code != 200: exit()

	# START STREAM
	r = api.request('tweets/search/stream',{'expansions':EXPANSIONS,'tweet.fields':TWEET_FIELDS,'user.fields':USER_FIELDS})
	print(f'[{r.status_code}] START...')
	if r.status_code != 200: exit()
	for item in r:
		print(item)

except TwitterRequestError as e:
	print(e.status_code)
	for msg in iter(e):
		print(msg)

except TwitterConnectionError as e:
	print(e)

except Exception as e:
	print(e)
```

But, i got this error 
`[400] RULE ADDED: {"errors":[{"parameters":{"add":["value"]},"message":"The query parameter [add] is not one of [expansions,tweet.fields,media.fields,poll.fields,place.fields,user.fields]"}],"title":"Invalid Request","detail":"One or more parameters to your request was invalid.","type":"https://api.twitter.com/2/problems/invalid-request"}`

How to fix the error?
Thank you

**Comment by geduldig** [comment]
Change this line:
```
r = api.request('tweets/search/stream', {'add': [{'value':QUERY}]})
```
Missing `rule` in the endpoint:
```
r = api.request('tweets/search/stream/rule', {'add': [{'value':QUERY}]})
```

**Comment by ardiantovn** [comment]
Hi..., thank you. It works using `rules`
`r = api.request('tweets/search/stream/rule', {'add': [{'value':QUERY}]})`
Thank you...🙏

**Comment by ardiantovn** [comment]
Hi, i want to ask some questions again. 
1. How to get the `full_text` result? Using the script above, i got truncated `tweet_text`. And if the tweet is truncated, I don't get hashtags entities because the hashtags is located at the end of the tweet.
2. I get `USER_FIELDS` data, but this entities only contains the mentioned user's entity. How to get author's `USER_FIELDS`  entities?
