### ISSUE TITLE
Handle v2 expansion data in TwitterPager

### ISSUE THREAD

**Issue by dylancaponi** [geduldig/TwitterAPI#156]
I'd like to expand the TwitterPager to paginate queries and append results with v2 field expansions.

Here are example query components:
```
ENDPOINT = 'tweets/search/recent'
EXPANSIONS = 'attachments.media_keys'
MEDIA_FIELDS = ['duration_ms',
                'height',
                'media_key',
                'preview_image_url',
                'type',
                'url',
                'width',
                'public_metrics',
                'non_public_metrics',
                'organic_metrics']
```

Queries that use expansions have results with a nested structure.
These results have an 'includes' key that currently gets clobbered by `TwitterPager`
I'd like to just paginate and append to a giant list.

The quick and dirty way I see of modifying `class _RestIterable(object)` `__init__` [here](https://github.com/geduldig/TwitterAPI/blob/4d5c636aea15940907d021b1f6b7a8dc382ae2ad/TwitterAPI/TwitterAPI.py#L295):
```
        if 'errors' in resp:
            self.results = resp['errors']
        # add this >>>>
        elif 'includes' in resp:
            self.results = [resp]
        # <<<<<<
        elif 'statuses' in resp:
            self.results = resp['statuses'] 
```

... but I'm sure there's something more elegant.

Example structure of one page of results:
```
 {'data': [{'attachments': {'media_keys': ['12345']},
            'id': '12345',
            'text': 'some text'},
           {'attachments': {'media_keys': ['12345']},
            'id': '12345',
            'text': "some text'}],
  'includes': {'media': [{'duration_ms': 12345,
                          'height': 12345,
                          'media_key': '12345',
                          'non_public_metrics': {'playback_0_count': 12345,
                                                 'playback_100_count': 12345,
                                                 'playback_25_count': 12345,
                                                 'playback_50_count': 12345,
                                                 'playback_75_count': 12345},
                          'organic_metrics': {'playback_0_count': 12345,
                                              'playback_100_count': 12345,
                                              'playback_25_count': 12345,
                                              'playback_50_count': 12345,
                                              'playback_75_count': 12345,
                                              'view_count': 12345},
                          'preview_image_url': 'some url',
                          'public_metrics': {'view_count': 12345},
                          'type': 'video',
                          'width': 1080},
                          {'duration_ms': 12345,
                          'height': 12345,
                          'media_key': '12345',
                          'non_public_metrics': {'playback_0_count': 12345,
                                                 'playback_100_count': 12345,
                                                 'playback_25_count': 12345,
                                                 'playback_50_count': 12345,
                                                 'playback_75_count': 12345},
                          'organic_metrics': {'playback_0_count': 12345,
                                              'playback_100_count': 12345,
                                              'playback_25_count': 12345,
                                              'playback_50_count': 12345,
                                              'playback_75_count': 12345,
                                              'view_count': 12345},
                          'preview_image_url': 'some url',
                          'public_metrics': {'view_count': 12345},
                          'type': 'video',
                          'width': 1080},
                         ]},
  'meta': {'newest_id': '12345',
                'next_token': 'abc12345',
                'oldest_id': '12345',
               'result_count': 12345}}
```

**Comment by geduldig** [comment]
Hi,

Just to clarify, it is not `TwitterPager` that is "clobbering" the `includes` object. As you suggest in your fix, it is `_RestIterable` that is not returning the object.

I have a problem with this fix. The intention for `_RestIterable` is to return objects from a list that are similar. If it were to also return the `includes` object it would break or complicate this intention.

I view `_RestIterable` as a helper class that makes it easier for the user to iterate a result that is a list. In v1.1 the format for results with lists (tweets, ids, trends, etc) is a mess. The iterator was meant to provide a standard way of accessing these lists. In v2, I believe, the list results always are in the `data` object, which is much nicer. The `includes` object, however, is external to the list, and that's why I think it shouldn't get returned by the iterator.

The current way to access an object that is a property of the returned results `r` is as follows:
```python
r.json()['includes']
```
Likewise, `TwitterPager`, another helper class, works off of `_RestIterable` to make the results that contain a list appear stream-like -- one continuous stream of similar items. I could imagine the iterator for `TwitterPager` having an option for returning "extra" objects like `includes` or `meta`. Then, it is up to the client to parse each item to figure out what kind of object it is (i.e. a tweet object or an `includes` object). Does this sound reasonable?

Jonas

**Comment by pedrorio** [comment]
Would you be open to a PR that inserted some v2 extensions inside the status object?

For instance, including a 'author' object if the author_id was in the requested expansions.

**Comment by geduldig** [comment]
Would the insertion occur inside `_RestIterable`?
I think I'd be open if it is not the default behavior. There would need to be a way to "turn on" this feature.

**Comment by geduldig** [comment]
I like your idea and will start work on it. But, let me know if you already have something in the works, that I should wait for.

**Comment by dylancaponi** [comment]
It's minor changes and I was testing with this branch:
https://github.com/dylancaponi/TwitterAPI/tree/add-user-tweets-timeline-v2

**Comment by geduldig** [comment]
I prefer what @pedrorio had suggested. I haven't thought much about it, but I imagine in `__init__` of `_RestIterable` that data from the `includes` section would be inserted into tweets in the `data` section. Also, `__init__ ` would take an optional argument to turn on or off this feature. Default should be off.

**Comment by geduldig** [comment]
New feature added in v2.6.8: tweet hydration for v2 endpoints. This will work for `search`, `stream` and any other endpoint that supports Twitter expansions.

For syntax, see new "hydrate" examples in "examples/v2". A new optional parameter `hydrate_tweets=True` for `TwitterAPI.requests()` and `TwitterPager` constructor has been added.

By default `hydrate_tweets=False` which means JSON results will contain a `data` section and a seperate `includes` if Twitter expansions are included. To hydrate means to insert `includes` back into `data`. This is done by replacing the expanded ID's in `data` with the property values of those IDs in `includes`.

**Comment by geduldig** [comment]
EXAMPLE...

	TWEET_ID = '1260294888811347969'
	EXPANSIONS = 'author_id'

	r = api.request(f'tweets/:{TWEET_ID}', {'expansions':EXPANSIONS}, hydrate_tweets=True)

	print('\nHYDRATED OUTPUT')
	for item in r:
		print(json.dumps(item, indent=2))

	print('\nRAW OUTPUT')
	print('\n', json.dumps(r.json(), indent=2))

**Comment by geduldig** [comment]
HYDRATED OUTPUT
    {
        "author_id": {
            "id": "783214",
            "name": "Twitter",
            "username": "Twitter"
        },
        "id": "1260294888811347969",
        "text": "Don\u2019t miss the Tweets about your Tweet. \n\nNow on iOS, you can see Retweets with comments all in one place. https://t.co/oanjZfzC6y"
    }

    RAW OUTPUT
    {
        "data": {
            "author_id": "783214",
            "id": "1260294888811347969",
            "text": "Don\u2019t miss the Tweets about your Tweet. \n\nNow on iOS, you can see Retweets with comments all in one place. https://t.co/oanjZfzC6y"
        },
        "includes": {
            "users": [
                {
                    "id": "783214",
                    "name": "Twitter",
                    "username": "Twitter"
                }
            ]
        }
    }
