### ISSUE TITLE
ActivityAPI: Non-200 response code during CRC GET request (i.e. 404, 500, etc).

### ISSUE THREAD

**Issue by cicciob95** [geduldig/TwitterAPI#159]
I'm trying to register a Twitter Webhook with the following code:
        r = twitterAPI.request('account_activity/all/:{}/webhooks'.format(self.env_name), {'url': self.webhook_url})
        if r.status_code == 200:
            logger.error("Twitter Webhook Setup successed: {}".format(r.text))
        else:
            logger.error("Twitter Webhook Setup Failed: {}".format(r.text))
but I always get  "Non-200 response code during CRC GET request (i.e. 404, 500, etc)" error, even if the registered endpoint does not receive any requests with a crc_token.

**Comment by geduldig** [comment]
I don't use webhooks so I don't think I can help you, unless you believe TwitterAPI is doing something improperly. You might want to confirm that you are using webhooks properly by trying the same request using CURL.

**Comment by cicciob95** [comment]
These days I have tried several ways and TwitterAPI behaves correctly. The problem is due to the reverse proxy I use to forward requests locally. Thanks for your time.
