### ISSUE TITLE
The number of text words returned by search is limited

### ISSUE THREAD

**Issue by stjianbin** [geduldig/TwitterAPI#160]
![image](https://user-images.githubusercontent.com/34124482/105182078-95ec9100-5b67-11eb-91de-9a815debc66f.png)
How to solve the word limit returned

**Comment by stjianbin** [comment]
{
            "created_at": "Sun Feb 25 18:11:01 +0000 2018",
            "id": 967824267948773377,
            "id_str": "967824267948773377",
            "text": "**From pilot to astronaut, Robert H. Lawrence was the first African-American to be selected as an astronaut by any na… https://t.co/FjPEWnh804**",
            "truncated": true,
            "entities": {
                "hashtags": [],
                "symbols": [],
                "user_mentions": [],
                "urls": [
                    {
                        "url": "https://t.co/FjPEWnh804",
                        "expanded_url": "https://twitter.com/i/web/status/967824267948773377",
                        "display_url": "twitter.com/i/web/status/9…",
                        "indices": [
                            117,
                            140
                        ]
                    }
                ]
            },

**Comment by stjianbin** [comment]
the number of "text" is limited

**Comment by geduldig** [comment]
Does https://github.com/geduldig/TwitterAPI/issues/122 answer your question?

**Comment by stjianbin** [comment]
> Does #122 answer your question?

Thank you， this is the key
