### ISSUE TITLE
Add support for promoted_tweets endpoint

### ISSUE THREAD

**Issue by dylancaponi** [geduldig/TwitterAPI#163]
The full endpoint is: `accounts/:account_id/promoted_tweets`

Reference is here:
https://developer.twitter.com/en/docs/twitter-ads-api/campaign-management/api-reference/promoted-tweets

@geduldig I'm starting to work on this if you have suggestions.

**Comment by geduldig** [comment]
Starting work on? Adding this endpoint to `constants.py`? Suggestions for?

**Comment by geduldig** [comment]
The Ads API is already supported by Twitter API, so adding endpoints is rather simple. Simply find the section in `constants.py` that contains endpoints for Ads. Then insert the new one alphbetically. When an endpoint, like this one, contains a parameter that is part of the URL, you must use ":PARAM" for the parameter. See other endpoints for examples.

**Comment by dylancaponi** [comment]
Great! Wasn't sure if there would be other changes required for TwitterPager etc. Notes in `constants.py` says the ads endpoints are not tested.

**Comment by geduldig** [comment]
Not tested because I don't have access to this API. So, please use and if it works we can remove "not tested".
