### ISSUE TITLE
OAuth 2.0 Bearer Token authentication

### ISSUE THREAD

**Issue by caimeng2** [geduldig/TwitterAPI#165]
I tried to do a full-archive search using TwitterPager with Twitter's new Academic Research product (version 2 endpoint) and got "TwitterRequestError: ('{"title":"Unsupported Authentication","detail":"Authentication with OAuth 1.0a User Context is forbidden. Please, make the request with OAuth 2.0 Bearer Token authentication.","type":"https://api.twitter.com/2/problems/unsupported-authentication"}',) (403)..." I used the old token key& token secret authentication. Does this package support bearer token authentication?

**Comment by geduldig** [comment]
Yes, it supports OAuth 2 Bearer Token. Here is an example:

https://github.com/geduldig/TwitterAPI/blob/master/examples/v1.1/connect_using_oauth.py

**Comment by caimeng2** [comment]
Wonderful! Thank you.
