### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [geduldig/TwitterAPI#172]
For distribution packages it's often required or recommended to run the tests.

Could you please tag the source when you make a release?

This would allow package maintainers to use the GitHub releases and as those archive will contain the `tests` directory to run the tests during the package build process.

Thanks

**Comment by geduldig** [comment]
Will do.

Thanks for the suggestion.

**Comment by fabaff** [comment]
Could you do it for 2.6.6 retrospectively?

**Comment by geduldig** [comment]
Done

**Comment by fabaff** [comment]
Thanks again for the super quick reaction.
