### ISSUE TITLE
Questions about endpoints using

### ISSUE THREAD

**Issue by gawainhuang** [geduldig/TwitterAPI#177]
I am new to Twitter API. So I am confused with the conception endpoint, can I just think of the endpoint as the resource URL given in the examples by Twitter API docs. 
Let me be more specific, take `curl "https://api.twitter.com/2/tweets/1067094924124872705" -H "Authorization: Bearer $BEARER_TOKEN"` show in [here](https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets-id) as an example. Does `'tweets/{TWEET_ID}'` is the exactly para that I am supposed to convey into `api.request()`. If yes, but why you used `f'tweets/:{TWEET_ID}'` in your [example](https://github.com/geduldig/TwitterAPI/blob/master/examples/v2/lookup_tweet.py).
And could you tell me how to find the correct format if I want to use different endpoint as para in api.request(). Thank your for your work.

**Comment by gawainhuang** [comment]
I've seen there is another API [here](https://developer.twitter.com/en/docs/twitter-api/tweets/lookup/api-reference/get-tweets-id) which using `tweets/:id`. And there is an endpoint URL like `https://api.twitter.com/2/tweets/:id`. But I still wonder the exact meaning of `f` in `f'tweets/:{TWEET_ID}'`, and on which occasion should I use it?

**Comment by geduldig** [comment]
In python, strings that are prefixed with "f" are known as f-strings or formattted strings. Anything in curly brackets gets replaced by the value of the variable inside.

**Comment by gawainhuang** [comment]
Thanks a lot for your explanation. However, I notice that you only give an example of `GET /2/tweets/:id`, and when I like to use `GET /2/tweets` I encounter an error that shows `Invalid endpoint`, here are how I used the method. Could you tell me how can I correct the code or the correct way in order to search multi tweets at a time by using the look-up method?
```python
TWEET_ID = ['1241938422672920576','1241938422685564928','1241938422727454722','1241938422748463104','1241938422782189568']
api = TwitterAPI(o.consumer_key, o.consumer_secret, o.access_token_key, o.access_token_secret, api_version='2')
r = api.request(f'tweets/{TWEET_ID}',
	{
		'expansions': EXPANSIONS,
		'tweet.fields': TWEET_FIELDS,
	}, 
	hydrate_tweets=True)
```

**Comment by geduldig** [comment]
You are mixing two different endponts and you are supplying the tweet ids paramater incorrectly.

The two endpoints are:
2/tweets
2/tweets/:id

You should look at the docs for each. They tell you that the first endpoint takes a "query parameter" called `ids` which is a string of comma-separated tweet ids. The second endpoint takes one tweet id specificed as a "path parameter".

So, your code, which is getting info for a list of tweets, has two problems. One, `TWEET_ID` should be specified as a "query parameter." Two, `TWEET_ID` should be converted to a string from a list.
```python
TWEET_IDS = ['1241938422672920576','1241938422685564928','1241938422727454722','1241938422748463104','1241938422782189568']
r = api.request(f'tweets',
	{
		'ids': ','.join(TWEET_IDS),
		'expansions': EXPANSIONS,
		'tweet.fields': TWEET_FIELDS,
	}, 
	hydrate_tweets=True)
```
Alternatively, if you want to use the endpoint with a single tweet id, you would specifiy TWEET_ID in the path but do not forget the colon.
````python
TWEET_ID = '1067094924124872705'
r = api.request(f'tweets/:{TWEET_ID}',
	{
		'expansions': EXPANSIONS,
		'tweet.fields': TWEET_FIELDS,
	}, 
	hydrate_tweets=True)
```

**Comment by gawainhuang** [comment]
It works! Thanks.
