### ISSUE TITLE
Some fields are not returned in tweets/search/all

### ISSUE THREAD

**Issue by matnado** [geduldig/TwitterAPI#178]
I am trying to do a query in the 'tweets/search/all' API. I have noticed that only tweet and user fields are returned. In particular, I am most interested in geo-related fields. Below you find the query with some of the parameters defined. 

```
string_expansions = 'attachments.poll_ids,attachments.media_keys,author_id,entities.mentions.username,geo.place_id,in_reply_to_user_id,referenced_tweets.id,referenced_tweets.id.author_id'
place_fields = 'contained_within,country,country_code,full_name,geo,id,name,place_type'
tweet_fields ='attachments,author_id,context_annotations,conversation_id,created_at,entities,geo,id,in_reply_to_user_id,lang,public_metrics,possibly_sensitive,referenced_tweets,reply_settings,source,text,withheld'

api = TwitterAPI(consumer_key, consumer_secret, access_token_key, access_token_secret, auth_type='oAuth2', api_version='2')
r = api.request('tweets/search/all', 
        {
            'query':string_seeds,
            'start_time': start_time,
            'end_time': end_time,
            'max_results': max_results,
            'expansions':string_expansions,
            'media.fields':string_media_fields,
            'place.fields':string_place_fields,
            'poll.fields':string_poll_fields,
            'tweet.fields':string_tweet_fields,
            'user.fields':string_user_fields
        },
                   hydrate_tweets=True)
```

The only **location** returned is in _r.json()['includes']['users']_ . No other geo related parameter is returned in _r.json()['data']_ and by printing _r.json()['includes'].keys()_ I only get _dict_keys(['users', 'tweets'])_, so I believe that the other fields are missing

Please let me know if I am missing something or I should provide you with more information, 
Thanks

**Comment by geduldig** [comment]
Can you post your exact query -- with all fields and expansions?

**Comment by matnado** [comment]
Thank you for your quick reply. Below you find my query.. I tried different keywords: `vax`; `vacc`; `vaccine`; `pizza`; `pizza or drink`. 
- For the last two keywords if I print  _r.json()['includes'].keys()_ return _dict_keys(['users', 'tweets'])_ 
- For the middle keyword if I print _r.json()['includes'].keys()_ return _dict_keys(['users', 'tweets', 'media'])_ 
- For the last two keywords if I print  _r.json()['includes'].keys()_ return _dict_keys(['users', 'tweets', 'media', 'place'])_ 

Since I am only changing the keyword, I guess now that if a field is all empty is not returned. Am I correct? 
So this would mean that if at some point the 'place' field is not empty it is returned. The same goes for columns like 'geo'; which in my case are present only in the 'data' dictionary of the last two keywords. Since most of these data would be analysed over time and multiple queries aggregated, wouldn't be easier to always return all fields and columns even if empty?

Thanks again for your time

---------------------------------------------------------------------------------------------------------------

```
import requests
from TwitterAPI import TwitterAPI, TwitterOAuth, TwitterRequestError, TwitterConnectionError
import pandas as pd
import datetime

api = TwitterAPI(consumer_key, consumer_secret, access_token_key, access_token_secret, auth_type='oAuth2', api_version='2')

start_time = '2021-01-01T00:00:00Z'
end_time = '2021-03-01T00:00:00Z'
max_results = 10#500
string_seeds = 'vacc'#'pizza OR drink'#'vaccine'#
string_expansions = 'attachments.poll_ids,attachments.media_keys,author_id,entities.mentions.username,geo.place_id,in_reply_to_user_id,referenced_tweets.id,referenced_tweets.id.author_id'
string_place_fields = 'contained_within,country,country_code,full_name,geo,id,name,place_type'
string_tweet_fields ='attachments,author_id,context_annotations,conversation_id,created_at,entities,geo,id,in_reply_to_user_id,lang,public_metrics,possibly_sensitive,referenced_tweets,reply_settings,source,text,withheld'
string_media_fields = 'duration_ms,height,media_key,preview_image_url,type,url,width,public_metrics'
string_poll_fields = 'duration_minutes,end_datetime,id,options,voting_status'
string_user_fields = 'created_at,description,entities,id,location,name,pinned_tweet_id,profile_image_url,protected,public_metrics,url,username,verified,withheld'

api = TwitterAPI(consumer_key, consumer_secret, access_token_key, access_token_secret, auth_type='oAuth2', api_version='2')
r = api.request('tweets/search/all', 
        {
            'query':string_seeds,
            'start_time': start_time,
            'end_time': end_time,
            'max_results': max_results,
            'expansions':string_expansions,
            'media.fields':string_media_fields,
            'place.fields':string_place_fields,
            'poll.fields':string_poll_fields,
            'tweet.fields':string_tweet_fields,
            'user.fields':string_user_fields
        },
                   hydrate_tweets=True)

r.json()['includes'].keys()
```

**Comment by geduldig** [comment]
Unfortunately, I do not have an academic account, so I cannot use `tweets/search/all`. I did a similar test with `tweets/search/recent` instead. In my test, I kept only the place fields, since that was your question. I also changed the query to one that seems to return more results with place fields.

This does return `geo` and other location data for me. It's very likely the reason you are seeing none is because, in general, very few tweets include location data. First, try the code below to see if you get location data. If you do, try a similar request using `tweets/search/all` and see if that also returns tweets with location data.

```python
from TwitterAPI import TwitterAPI, TwitterOAuth, TwitterRequestError, TwitterConnectionError
import json

string_seeds = '"another gray day"'
string_expansions = 'attachments.poll_ids,attachments.media_keys,author_id,entities.mentions.username,geo.place_id,in_reply_to_user_id,referenced_tweets.id,referenced_tweets.id.author_id'
string_place_fields = 'contained_within,country,country_code,full_name,geo,id,name,place_type'

o = TwitterOAuth.read_file()
api = TwitterAPI(o.consumer_key, o.consumer_secret, auth_type='oAuth2', api_version='2')

r = api.request('tweets/search/recent',
        {
            'query': string_seeds,
            'expansions':string_expansions,
            'place.fields':string_place_fields,
        },
        hydrate_tweets=True)

for item in r:
        print(json.dumps(item, indent=2))
```

**Comment by matnado** [comment]
Yes I checked again and it returns the field only when it is not nan. Now that I got it I am able to get everything I need, Thanks
It may be worth mentioning in your examples that columns like 'geo' are returned only if the field 'place' is not nan. This would help when multiple queries are done and their results aggregated 
Thanks again and enjoy the rest of your day

**Comment by geduldig** [comment]
What is "nan"? Does that mean "not a number"?

The reason I don't go into detail about how the API works is because I would  be repeating what is already better explained in Twitter's own docs. My library actually contains no code that is specific to any of the endpoints. For instance, what parameters are accepted and what columns are returned. For this information it is best to directly to Twitter's own API docs.
