### ISSUE TITLE
"direct_messages/events/destroy/123456" unsupported

### ISSUE THREAD

**Issue by Ali-NH** [geduldig/TwitterAPI#179]
Hello,

[constants.py](https://github.com/geduldig/TwitterAPI/blob/master/TwitterAPI/constants.py)

I'm trying to delete a direct message using 'direct_messages/events/destroy/123456'

but i'm getting **'Exception: Endpoint "direct_messages/events/destroy/123456" unsupported'**

 I want to know if i'm doing something wrong?

api = TwitterAPI(111, 222, 333 , 444)
r =  api.request('direct_messages/events/destroy/123456').json()

**Comment by geduldig** [comment]
This endpoint uses a "path parameter" for the tweet id, so a colon is required.
```python
r = api.request('direct_messages/events/destroy/:123456').json()
```

**Comment by Ali-NH** [comment]
Same problem

For Example:

`{'events': [{'type': 'message_create', 'id': '1372274530706685974', 'created_timestamp': '1616010718405', 'message_create': {'target': {'recipient_id': '258546504'}, 'sender_id': '1097843103413817344', 'source_app_id': '3033300', 'message_data': {'text': 'Hi1', 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': []}}}}, {'type': 'message_create', 'id': '1372264010536648709', 'created_timestamp': '1616008210201', 'message_create': {'target': {'recipient_id': '258546504'}, 'sender_id': '1097843103413817344', 'source_app_id': '3033300', 'message_data': {'text': 'Hi2', 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': []}}}}], 'apps': {'3033300': {'id': '3033300', 'name': 'Twitter Web App', 'url': 'https://mobile.twitter.com'}}}`

```
api = TwitterAPI(111, 222, 333 , 444)
r = api.request('direct_messages/events/destroy/:1372274530706685974').json()
```

Error:

`Exception: Endpoint "direct_messages/events/destroy/:PARAM" unsupported`

**Comment by geduldig** [comment]
Sorry, my mistake. I assumed `direct_messages/events/destroy` took a path parameter because that is how you wrote the request originally. I just looked up the endpoint in Twitter's [docs](https://developer.twitter.com/en/docs/twitter-api/v1/direct-messages/sending-and-receiving/api-reference/delete-message-event), and I see it takes a query parameter `id`.
```python
r = api.request('direct_messages/events/destroy', {'id':1372274530706685974}).json()
```

**Comment by Ali-NH** [comment]
Thanks alot! it worked but after the DM is deleted i'm getting this

```
Traceback (most recent call last):
  File "C:/Users/User/Desktop/testing.py", line 29, in <module>
    api.request('direct_messages/events/destroy', {'id': 1372274530706685974}).json()
  File "X:\Program Files\Python\Python38-32\lib\site-packages\TwitterAPI\TwitterAPI.py", line 248, in json
    return self.response.json(**kwargs)
  File "X:\Program Files\Python\Python38-32\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "X:\Program Files\Python\Python38-32\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "X:\Program Files\Python\Python38-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "X:\Program Files\Python\Python38-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
