### ISSUE TITLE
How to view all tweets and replies of a user

### ISSUE THREAD

**Issue by stjianbin** [geduldig/TwitterAPI#181]
What api can be used to achieve this function？   Help me Thanks

**Comment by geduldig** [comment]
You should start by looking at the Twitter API docs [here](https://developer.twitter.com/en/docs/twitter-api). Then decide if you want to use v1.1 or v2 of the API.

[v1.1 user timelines](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/timelines/overview)
[v2 user timelines](https://developer.twitter.com/en/docs/twitter-api/tweets/timelines/introduction)

Either will return a maximum of 3200 tweets. If that is not enough you must use [Premium v1.1](https://developer.twitter.com/en/docs/twitter-api/premium/search-api/overview).

**Comment by stjianbin** [comment]
Thanks,  it's worth

**Comment by stjianbin** [comment]
Another question, in the returned data, does Twitter have any comment data?

**Comment by stjianbin** [comment]
How to get the comment data in tweets

**Comment by geduldig** [comment]
What is "comment data"? There is nothing by this name. First, read the docs. They specify exactly what is returned.

**Comment by stjianbin** [comment]
![image](https://user-images.githubusercontent.com/34124482/112162740-4e49ba80-8c27-11eb-8432-5c2c9815abf5.png)

reply data

**Comment by geduldig** [comment]
Replies come with the user timeline. Did you look at the documentation?
