### ISSUE TITLE
_init__() got an unexpected keyword argument 'api_version'

### ISSUE THREAD

**Issue by brandnamewater** [geduldig/TwitterAPI#182]
I'm attempting to get users tweets by USER_ID like here: https://github.com/geduldig/TwitterAPI/blob/master/examples/v2/user_tweets.py

The error:  __init__() got an unexpected keyword argument 'api_version'

If I don't use api_version='2' I get  Endpoint "users/:PARAM/tweets" unsupported.

I reinstalled pip install TwitterAPI but I had the most recent version.

Is there another version I need to use?

**Comment by geduldig** [comment]
Do you know what version of TwitterAPI you have installed?
When you ran `pip install TwitterAPI` did you  include the `--upgrade` parameter?

You must specify `api_version='2'`, otherwise version 1.1 is assumed. Version 1.1 doesn't have "users/:PARAM/tweets" as an endpoint.
