### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [geduldig/TwitterAPI#183]
Could you please tag the source? The latest release available on GitHub is 2.6.8. Otherwise I have to migrate the Fedora and the NixOS package and would no longer be able to run the tests during the package build process.

Thanks.

**Comment by geduldig** [comment]
v2.6.10 now is tagged. I'll do that more consistently in the future. Thanks!

**Comment by fabaff** [comment]
Thank you very much.
