### ISSUE TITLE
What API can be used to judge whether a tweeter has opened the private message function

### ISSUE THREAD

**Issue by stjianbin** [geduldig/TwitterAPI#184]
What API can be used to judge whether a tweeter has opened the private message function

**Comment by stjianbin** [comment]
![image](https://user-images.githubusercontent.com/34124482/114825739-2bab5b80-9df9-11eb-9fbc-9d1127c5fda6.png)

**Comment by stjianbin** [comment]
![image](https://user-images.githubusercontent.com/34124482/114825875-54335580-9df9-11eb-84a8-ade2718b1fba.png)
![image](https://user-images.githubusercontent.com/34124482/114825902-5dbcbd80-9df9-11eb-9133-03e59dad65dd.png)

**Comment by geduldig** [comment]
I don't think that exists. You can post the question on https://twittercommunity.com/.
