### ISSUE TITLE
[Question] Handling of too many requests

### ISSUE THREAD

**Issue by santoshbs** [geduldig/TwitterAPI#186]
I was wondering if this package handles errors arising from too many requests made to a Twitter API made in a given time slot.

**Comment by geduldig** [comment]
If you are using the `TwitterAPI.request` method, you should catch the appropriate error and throttle your requests. If your are using the `TwitterPager` helper class, it will automatically throttle for you. The class also takes an optional `wait` argument to set the interval between requests.

The docs are sorely out-of-date. I'll be working on this in the next couple of weeks. Exceptions to be caught are listed [here](https://twitterapi.readthedocs.io/en/latest/twittererror.html).
