### ISSUE TITLE
Media keys Hydrate not returning information about all the media keys linked to a tweet.

### ISSUE THREAD

**Issue by marcelo-mascarenhas** [geduldig/TwitterAPI#193]
Hello, how are you all doing?
I have been developing a twitter collector for some time, but only know i realized one thing, and i would like to know if it is normal...
When you request the media_keys of a specific tweet, it usually returns all of them. However, when you add Hydrate, it doesn't return the information about ALL the media keys, just one... 
For instance:
`{
  "attachments": {
    "media_keys": [
      "3_1413529663599566848",
      "3_1413529663591227395"
    ],
    "media_keys_hydrate": [
      {
        "height": 892,
        "media_key": "3_1413529663591227395",
        "width": 1125,
        "type": "photo",
        "url": "https://pbs.twimg.com/media/E53dvWXVIAMEPRQ.jpg"
      }
    ]
  },
  "id": "1413529669509390336",
  "text": "Apple Music Philippines \ud83c\uddf5\ud83c\udded\n\nTop Songs \ud83c\udfb6\n#1 Permission to Dance \n#2 Butter \n\nTop Videos \ud83d\udcf9\n#1 Permission to Dance\n#2 Butter \n\nPH ARMYs DID THAT. \ud83e\udd73\ud83e\udd73\ud83e\udd73\n\n#PermissionToDance @BTS_twt https://t.co/FlK5kg5267"
}
`
Is it just that Twitter's API doesn't send the information, or is it something wrong with the library ( or, in the worst case, with my code, haha)?
Thanks in advance!

**Comment by marcelo-mascarenhas** [comment]
Fix #198

**Comment by marcelo-mascarenhas** [comment]
Fix #198

**Comment by geduldig** [comment]
Can you provide a simple code example?

**Comment by geduldig** [comment]
Fixed in v2.7.8.
