### ISSUE TITLE
Way to access x-rate-limit-reset header when using TwitterPager

### ISSUE THREAD

**Issue by aks-71** [geduldig/TwitterAPI#199]
Hey, I am using `TwitterPager`, and is there a way to access the `x-rate-limit-reset` header when the error status code is 429. I see that `TwitterPager` raises a `TwitterRequestError` and it only has `status_code` and `msg`.
Can I get the `x-rate-limit-reset` header from there or anywhere else?
Thanks a lot!!

Edit:
I see a `get_quota` method in `TwitterResponse` but there is not way to access it from TwitterPager

**Comment by geduldig** [comment]
No, that's not possible.

You can get the rate limit status via a request - https://developer.twitter.com/en/docs/twitter-api/v1/developer-utilities/rate-limit-status/api-reference/get-application-rate_limit_status.

Also, you can override the default wait interval that TwitterPager uses between requests so you never get the 429 error.

**Comment by aks-71** [comment]
Okay thanks!
