### ISSUE TITLE
Retweets are getting truncated 

### ISSUE THREAD

**Issue by OmiWakode** [geduldig/TwitterAPI#200]
Hi, i am using the TwitterAPI V2 endpoint for sampled stream, but the returned tweet text is always truncated to 140 characters approximately. Any idea how to resolve this?

**Comment by geduldig** [comment]
Hi -
Without seeing your request I cannot be sure. V2 does not truncate tweets, although V1.1 does truncate tweets by default. You may be seeing an embedded tweet that has been truncated. See this discussion:

https://stackoverflow.com/questions/63540330/get-extended-full-text-tweets-in-twitter-api-v2

Jonas
