### ISSUE TITLE
Wrong documentation version on gh-pages

### ISSUE THREAD

**Issue by NeodymiumFerBore** [geduldig/TwitterAPI#201]
Hello. The documentation on github-pages is not up to date.

---

Actual version on github-pages (from the link in README):

`TwitterAPI.TwitterAPI.request`: parameters:
> `hydrate_tweets` – Boolean determining whether to insert expansion data from “includes” directly into the tweet “data” structure. False (default) does not hydrate. True hydrates.

---

Version in branch 2.7.5 (actual version on pypi) (built in locally):

`TwitterAPI.TwitterAPI.request`: parameters:
>`hydrate_type` – HydrateType or int Do not hydrate - NONE or 0 (default) Append new field with ‘_hydrate’ suffix with hydrate values - APPEND or 1 Replace current field value with hydrate values - REPLACE or 2

---

In version 2.7.5 (I didn't check previous versions), `hydrate_tweets` is not a `request` parameter anymore, replaced by `hydrate_type`.

**Comment by geduldig** [comment]
Should be good now.
