### ISSUE TITLE
lang filtering does not seem to work

### ISSUE THREAD

**Issue by hwisunbae** [geduldig/TwitterAPI#205]
I am using premium search API, want to filter by language to get only English tweets.

Please investigate how I can filter tweets by language.
These are the ways I've tried.
```python
r = api.request('tweets/search/%s/:%s' % (PRODUCT, LABEL), 
                {'query':SEARCH_TERM, 
                'maxResults':'500',
                'lang': 'en'})

```

```python
r = api.request('tweets/search/%s/:%s' % (PRODUCT, LABEL), 
                {'query':'pizza -lang:en', 
                'maxResults':'500''})

```

**Comment by geduldig** [comment]
Premium search operators are listed here:
https://developer.twitter.com/en/docs/twitter-api/premium/search-api/overview#AvailableOperators

No hyphen. Use instead: 'query':'pizza lang:en'
