### ISSUE TITLE
Bearer Token Issue with Academic Access in Twitter API V2

### ISSUE THREAD

**Issue by mattandryc** [geduldig/TwitterAPI#214]
I run into the following exception when trying use "oAuth2" on the /tweets/search/all endpoint (api_version='2') with my consumer_key and consumer_secret:

"Error requesting bearer access token: access_token"

It seems the request in [BearerAuth.py](https://github.com/geduldig/TwitterAPI/blob/894b5020c78b9021c76ca00a80ce9ed046190d1e/TwitterAPI/BearerAuth.py#L44) is not returning the bearer token associated with my app (strangely I get a Not Authorized 401 response).

Twitter's official documentation points to grabbing the bearer token from the developer dashboard directly → https://developer.twitter.com/en/docs/authentication/oauth-2-0/bearer-tokens as opposed to using the POST oauth2/token endpoint.

Has anyone else run into this issue?

**Comment by geduldig** [comment]
Make sure OAuth2 is enabled in the Developer Portal under "Keys and tokens".
