### ISSUE TITLE
Authenticating error (api_version='2')

### ISSUE THREAD

**Issue by 965realestate** [geduldig/TwitterAPI#226]
Is there a problem with authentication requests or I'm doing something wrong?

I tried the [Twitters API v2](https://github.com/twitterdev/postman-twitter-api) postman with (OAuth 1.0) Consumer Key, Consumer Secret, Access Token, Token Secret after that creating a tweet with Twitters API v2 it worked perfectly.

code:
```
# Consumer Keys
consumer_key = ??'
consumer_secret = '??'

# Access Token and Secret
access_token_key = '??'
access_token_secret = '??'

from TwitterAPI import TwitterAPI
api = TwitterAPI(consumer_key, consumer_secret, access_token_key, access_token_secret, api_version='2')

api.request('tweets', {'text': 'testing api'})
```

response:
> Request returned an error: 403 {"client_id":"26924600","detail":"When authenticating requests to the Twitter API v2 endpoints, you must use keys and tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer portal.","registration_url":"https://developer.twitter.com/en/docs/projects/overview","title":"Client Forbidden","required_enrollment":"Appropriate Level of API Access","reason":"client-not-enrolled","type":"https://api.twitter.com/2/problems/client-forbidden"}

**Comment by geduldig** [comment]
Looks good to me. Are you using the same credentials with Postman and TwitterAPI?

 I would add something to your code to confirm that your credentials are valid.

**Comment by 965realestate** [comment]
Yes, I'm using the same exact credentials with Postman and TwitterAPI.

What code do I need to add that check my credentials are valid?

**Comment by geduldig** [comment]
You could try other enpoints, such as searching for tweets, that don't require write privileges. I'm really not sure what to tell you. It doesn't make sense that the same credentials would would work in one case and not in the other. Are those credentials associated with a Twitter developer project?

**Comment by geduldig** [comment]
The error you are receiving is from Twitter, so it's impossible to for me to look into the cause. There must be some difference between your requests in Postman and in TwitterAPI. It might be helpful to try the same request using another library such as twarc.

**Comment by geduldig** [comment]
I see one thing you are doing wrong. The 'tweets' request, by default uses HTTP GET. You need to use HTTP POST in order to upload a tweet. Try this...
`r = api.request('tweets', {'text':'a test to test'}, method_override='POST')`

**Comment by 965realestate** [comment]
> I see one thing you are doing wrong. The 'tweets' request, by default uses HTTP GET. You need to use HTTP POST in order to upload a tweet. Try this... `r = api.request('tweets', {'text':'a test to test'}, method_override='POST')`

> method_override='POST'

Thank you! Problem fixed

**Comment by qkxie** [comment]
I have the same error. even when I set method to post:

```
resp = api.request('tweets', {'text': 'testing api'}, method_override='POST')
```

It still return error message:

```
'{"title":"Forbidden","status":403,"detail":"Your client app is not configured with the appropriate oauth1 app permissions for this endpoint.","type":"https://api.twitter.com/2/problems/oauth1-permissions"}'
```

**Comment by geduldig** [comment]
@qkxie How are you creating your `api` object?

**Comment by qkxie** [comment]
@geduldig 

```python
api = TwitterAPI(consumer_key, consumer_secret, access_key, access_secret, api_version='2')
```
