### ISSUE TITLE
 OP_NO_TICKET SSL Option no longer supported by Twitter

### ISSUE THREAD

**Issue by PaulEdwardsAP** [geduldig/TwitterAPI#229]
As of 2023-08-04 Twitter have implemented a change such that having an SSL option of OP_NO_TICKET will cause a 200 response but an empty body. TwitterAPI  calls requests lib-> urllib3, which enables this flag by default

Suggested workaround from fireattacks comments here on the tweepy lib is working for me.

https://github.com/tweepy/tweepy/issues/2152

**Comment by geduldig** [comment]
I read through https://github.com/tweepy/tweepy/issues/2152. Are you sure this is still an issue? In that Tweepy thread, there are comments posted after you posted here that say the issue is no longer reproducible and that Twitter fixed the issue on their end. Can you confirm?

**Comment by PaulEdwardsAP** [comment]
> I read through [tweepy/tweepy#2152](https://github.com/tweepy/tweepy/issues/2152). Are you sure this is still an issue? In that Tweepy thread, there are comments posted after you posted here that say the issue is no longer reproducible and that Twitter fixed the issue on their end. Can you confirm?

Yup, confirmed this is now fixed by Twitter so this is no longer an issue
