### ISSUE TITLE
Streaming stops with ValueError on (presumably) malformed input data

### ISSUE THREAD

**Issue by reidpr** [geduldig/TwitterAPI#36]
I've had my `statuses/sample` stream crash a couple of times with the following traceback:

```
Traceback (most recent call last):
  File "[...]/quac/bin/collect", line 204, in main_real
    self.collect()
  File "[...]/quac/bin/collect", line 224, in collect
    for tweet in self.stream:
  File "[...]/lib/python3.4/site-packages/TwitterAPI/TwitterAPI.py", line 203, in __iter__
    yield json.loads(item.decode('utf-8'))
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 359, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Unterminated string starting at: line 1 column 1984 (char 1983)
```
The first one was after about 68 million tweets; the second I didn't count but it was 4 hours of collection, so a couple million is a decent guess.

I am guessing this is due to malformed data in the stream from Twitter, but I haven't verified this.

My preferred behavior would be to continue with the stream somehow, but I'm not sure best how to achieve this. The problem is that I'm not sure how Some options I came up with are:

1. Call `next()` explicitly in a try/except block. I can do this on my end, though if that is the recommended approach it might be worth noting in the documentation. It is a little ugly.
1. Create a wrapper iterator, as in http://stackoverflow.com/a/13654229.
1. Iterator skips the bad data silently. This is a convenient API but might mask real problems and prevents issuing a warning.
1. Iterator returns `None` or an error object of some kind on bad data (maybe the exception itself). This makes processing the results of iteration more complex but keeps the simple iteration API.

The first two approaches I can do on my end, though they are a little ugly. If this is the recommended approach, then it might be worth noting in the documentation.

Do you have an opinion or suggestions?

Thanks for your work on TwitterAPI.

**Comment by geduldig** [comment]
With the latest version (2.3) I have been streaming the sample stream for over a week without having to manually intervene. In addition to `TwitterConnectionError`, I added `TwitterRequestError`. By catching both these exceptions you can handle timeouts, stalls, and interrupted connections. I included my test code for a fault tolerant stream in [examples\sample_freq.py](https://github.com/geduldig/TwitterAPI/blob/master/examples/sample_freq.py). It demonstrates how to handle these exceptions, when to re-try a request and when to give up.

There is also this [doc](http://geduldig.github.io/TwitterAPI/faulttolerance.html) which contains a code example that is a little more concise.

Note: whenever a stream disconnection occurs you are likely to miss tweets. During stalls you will miss 90 seconds worth of tweets. In cases where missing a small percentage of tweets is not acceptable, you should start a new thread with a `search/tweets` request to backfill a gap in the stream.

**Comment by reidpr** [comment]
Jonas, thank you very much for your hard work on this issue and others. I will try it out and let you know if we encounter any issues.

At a higher level, we are using TwitterAPI to support some research papers. Thus, we would like to mention you in the acknowledgements sections. Do you want this, and if so, what name would you like to be acknowledged under? Feel free to e-mail me privately at `reidpr@lanl.gov` if you prefer.
