### ISSUE TITLE
ImportError: cannot import name ReadTimeout

### ISSUE THREAD

**Issue by FranciscoGutierrez** [geduldig/TwitterAPI#46]
I cant figure out why I'm getting the following error, any ideas?

````py
File "/root/.local/lib/python2.7/site-packages/TwitterAPI/TwitterAPI.py", line
9, in <module>
    from requests.exceptions import ConnectionError, ReadTimeout, SSLError
ImportError: cannot import name ReadTimeout
```

**Comment by geduldig** [comment]
I think you might have an old version of the `requests` library. Try upgrading the library.

**Comment by inonpeled** [comment]
I had a similar problem, and it turned out that I had two installations of the requests lib: a newer one in /usr/lib/ and an older one in /usr/local/lib/. Also, my system path was configured to first lookup in /usr/lib/ first. My solution was to manually delete the older lib.

**Comment by ZiTAL** [comment]
to install requests:
```
pip install requests
```
to upgrade:
```
pip install --upgrade requests
```

**Comment by LucasHMS** [comment]
Problem solved here o/ Just upgraded my version with the command that @ZiTAL said. Thanks!
