### ISSUE TITLE
Is there a way to stream all tweets by language and no other parameters?

### ISSUE THREAD

**Issue by goshcharlotte** [geduldig/TwitterAPI#47]
I'm trying to use 
```python
r = api.request('statuses/filter', {'lang':'en'})
```
to get all tweets from all locations that are in English, but it's returning the following error: 
```
> python testing.py
Traceback (most recent call last):
  File "testing.py", line 21, in <module>
    for item in r.get_iterator():
  File "/Library/Python/2.7/site-packages/TwitterAPI/TwitterAPI.py", line 203, in __iter__
    yield json.loads(item.decode('utf-8'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Is there a way to get this with the streaming api or is it just with the search or something?

Also a kind of unrelated question: does the location filter only work with integers? I'd like to search quite a specific location and I can't seem to search for very specific areas without getting errors.

**Comment by geduldig** [comment]
`statuses/filter` requires that you supply either a `track` parameter or a `locations` parameter. That is why your request fails. If you inspect `r.status_code` you will see your request failed with code 406.

The `locations` parameter takes either floats or integers.

Hope that helps you.

**Comment by goshcharlotte** [comment]
Thanks so much for answering this, it was very helpful.
Just one more thing though, when I use something like ```{'locations':'-0.266418,51.561705'}``` as my parameter, I'm still getting the same error? Sorry for commenting when this is closed.

**Comment by goshcharlotte** [comment]
Actually never mind, realised I was using the SE and NW coordinates instead of the SW and NE coordinates Twitter accepts... Thanks anyway!
