### ISSUE TITLE
Unable to pass a list in the user_id param

### ISSUE THREAD

**Issue by davidkurkov** [geduldig/TwitterAPI#49]
Description: When I try to make the 'list/members/create_all' API request using a list in the 'user_id' param, it fails to send the request with all the elements of the list - only the first one makes it through. Looking at the Requests Python Library, it looks like the param element needs to be appended with '[]' (i.e., 'user_id[]') to signify that the data is a list that needs to be sent. However, when I try to do this in the TwitterAPI request, I get a response back of a missing parameter. Is it possible to add the check for a list in 'user_id'?

Pre-Conditions:
-twitterapi==2.3.3 installed

Steps:
1. Authenticate with Twitter
2. Make this request: 
api.request('lists/members/create_all', {'list_id':10002, 'user_id':[18055737, 292116015, 23818581, 2890961, 1282121312, 344538987]})

Expected: All user_ids listed in the 'user_id' param are added as members to the list.
Actual: Only the first user_id list in the 'user_id' param is added as a member to the list.

Note: Requests Python Library documentation on passing lists in a param: http://docs.python-requests.org/en/latest/user/quickstart/

###

FROM DOC:

In order to pass a list of items as a value you must mark the key as referring to a list like string by appending [] to the key:

>>> payload = {'key1': 'value1', 'key2[]': ['value2', 'value3']}
>>> r = requests.get("http://httpbin.org/get", params=payload)
>>> print(r.url)
http://httpbin.org/get?key1=value1&key2%5B%5D=value2&key2%5B%5D=value3

###

**Comment by davidkurkov** [comment]
I just saw a workaround mentioned in https://github.com/geduldig/TwitterAPI/issues/26. The list needs to be passed in as a string in the 'user_id' field and it'll be accepted. Thanks for your time!

**Comment by geduldig** [comment]
That's correct. Parameters should be passed as strings.
