### ISSUE TITLE
POST friendships/create

### ISSUE THREAD

**Issue by lord0hypnos** [geduldig/TwitterAPI#50]
Hi when I try do this:
r = api.request('friendships/create', {'follow': 'false', 'user_id':userid})

I get this response:
r.text --->{"errors":[{"code":108,"message":"Cannot find specified user."}]}

r. headers ----> {'status': '403 Forbidden', 'x-response-time': '35', 'content-length': '65', 'x-twitter-response-tags': 'BouncerCompliant', 'content-disposition': 'attachment; filename=json.json', 'x-content-type-options': 'nosniff', 'x-connection-hash': '', 'set-cookie': 'lang=en, guest_id=; Domain=.twitter.com; Path=/; Expires=Sat, 01-Apr-2017 20:20:33 UTC', 'strict-transport-security': 'max-age=631138519', 'x-access-level': 'read-write', 'x-tsa-request-body-time': '0', 'expires': 'Tue, 31 Mar 1981 05:00:00 GMT', 'server': 'tsa_b', 'last-modified': 'Thu, 02 Apr 2015 20:20:33 GMT', 'x-xss-protection': '1; mode=block', 'pragma': 'no-cache', 'cache-control': 'no-cache, no-store, must-revalidate, pre-check=0, post-check=0', 'date': 'Thu, 02 Apr 2015 20:20:33 GMT', 'x-transaction': '', 'x-frame-options': 'SAMEORIGIN', 'content-type': 'application/json;charset=utf-8'}

r.response ----> <Response [403]>

Any idea why?

**Comment by geduldig** [comment]
Sounds like your `user_id` was bad.

**Comment by lord0hypnos** [comment]
Yes I took tweet ID not user ID. Sorry for unnecessary issue :(
