### ISSUE TITLE
Filter stream by track term AND location?

### ISSUE THREAD

**Issue by goshcharlotte** [geduldig/TwitterAPI#55]
Is it possible to pass two parameters with a streaming request? I swear I saw something about this in the documentation a while ago but cannot seem to find it again. I'm trying to do:
```
r = api.request('statuses/filter', {'track': filt, 'locations': location})
```

**Comment by geduldig** [comment]
Yes, you have it right.

**Comment by goshcharlotte** [comment]
I thought that was the case, but every time I run that with something like filt='#pizza' and location='-74,40,-73,41', I get tweets returned from the location but not containing the track term? Do you know why this might be the case?

**Comment by geduldig** [comment]
I would try the request with just "#pizza" and no location, to see if you are getting results.

What you are seeing is not out-of-the-ordinary. `track` and `locations` are not treated as AND'ed; they are OR'ed. So, you should see any results containing "#pizza" (if any) or any results from NYC. Twitter does not filter tweets that match both parameters.

Hope that helps.

**Comment by goshcharlotte** [comment]
Ohh ok that makes a lot more sense. Thanks much!
