### ISSUE TITLE
No NullHandler Attribute 

### ISSUE THREAD

**Issue by maxwelldonkoh** [geduldig/TwitterAPI#56]
I am getting this error.  'module' object has no attribute 'NullHandler. Using python 2.7. Help?

**Comment by geduldig** [comment]
Please post a short sample which produces this error.
Thanks!
Jonas

**Comment by maxwelldonkoh** [comment]
Just the from 'from TwitterAPI import TwitterAPI' produces the error. even without any other code.

**Comment by geduldig** [comment]
I'm not sure what's going on. I don't get this error myself on Mac or PC running Python 2.7.2 or 2.7.9. `NullHandler` has been included in Python beginning with version 2.7. Any other info you can provide? Did you use `python --version` to verify the version?

**Comment by maxwelldonkoh** [comment]
Python 2.7.6. And I'm actually using code similar to what you wrote in an article about counting tweets

**Comment by maxwelldonkoh** [comment]
I figured my IDE was using 2.6. However, I am getting another error. I'm fairly new to python. This is the traceback.

Traceback (most recent call last):
  File "/Users/maxwelldonkoh/PycharmProjects/algo/main.py", line 3, in <module>
    from TwitterAPI import TwitterAPI
  File "/Users/maxwelldonkoh/PycharmProjects/algo/TwitterAPI/TwitterAPI.py", line 6, in <module>
    from .BearerAuth import BearerAuth as OAuth2
  File "/Users/maxwelldonkoh/PycharmProjects/algo/TwitterAPI/BearerAuth.py", line 8, in <module>
    import requests
ImportError: No module named requests

**Comment by geduldig** [comment]
Glad you figured it out. There was a previous poster with exactly the same issue, so I'm curious how you ended up running a different version or what led you to think you were running a different version of Python. Maybe it will help others with this issue.

Jonas

**Comment by geduldig** [comment]
You need to update your requests library.
