### ISSUE TITLE
timelines endpoint

### ISSUE THREAD

**Issue by k0a1a** [geduldig/TwitterAPI#60]
are you plannoing to support https://api.twitter.com/1.1/timelines/timeline.json endpoint?

**Comment by geduldig** [comment]
Is that a valid endpoint? I cannot find it on the [dev site](https://dev.twitter.com/rest/public). Do you have a link the documentation?

**Comment by k0a1a** [comment]
my bad, 'timelines/timeline.json' is an obsolete name for https://api.twitter.com/1.1/collections/entries.json which is described here https://dev.twitter.com/rest/reference/get/collections/entries

**Comment by geduldig** [comment]
I never noticed the Collections API (or TON or Curator APIs for that matter). I can add all the endpoints for these APIs. If you are interested in submitting the patch yourself, all that should be required is updating [constants.py](https://github.com/geduldig/TwitterAPI/blob/master/TwitterAPI/constants.py). I should get to it this weekend or next.

**Comment by k0a1a** [comment]
yes, those APIs are a relatively new addition. I'm going to see if i can contribute a patch (in fact, I'm interested in Curator API too)

**Comment by geduldig** [comment]
How are you doing with the patch? Do you need help?

**Comment by geduldig** [comment]
I just got whitelisted for the Curator API and Collections API, so I will be adding support for them in the next week or so...

**Comment by geduldig** [comment]
Latest version (2.4.0) now has endpoints for Curator and Collections.
