### ISSUE TITLE
Multiple accounts on the same process.

### ISSUE THREAD

**Issue by luigifreitas** [geduldig/TwitterAPI#63]
It's possible to stream multiple accounts on the same .py file? I'm having trouble with memory usage running +300 script at the same time.

**Comment by geduldig** [comment]
I'm not sure what Twitter's policy is regarding multiple streams from the same IP. You might try asking the question on the [forum](https://twittercommunity.com/). 

Memory usage is handled by your code, so I can't help you there either.

**Comment by luigifreitas** [comment]
Thanks for the advice.
