### ISSUE TITLE
statuses/show not working

### ISSUE THREAD

**Issue by bosiakov** [geduldig/TwitterAPI#64]
```
>>> api.request('statuses/show', {'id': '627727032139448320'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/TwitterAPI/TwitterAPI.py", line 91, in request
    raise Exception('Endpoint "%s" unsupported' % endpoint)

Exception: Endpoint "statuses/show" unsupported
```

Is this a bug?
If not, is there a way to get information about a particular tweet?
Method - https://dev.twitter.com/rest/reference/get/statuses/show/%3Aid

**Comment by bosiakov** [comment]
I'm sorry to trouble you. I found it in the closed issues.
Maybe you should add this to documentation?

**Comment by geduldig** [comment]
Yes, you are not the first to ask about this. I'll add this to the docs.

**Comment by geduldig** [comment]
Example added to README.

More examples [here](http://geduldig.github.io/TwitterAPI/examples.html) and [here](https://github.com/geduldig/TwitterAPI/blob/master/examples/delete_last_tweet.py).
