### ISSUE TITLE
Stream theading

### ISSUE THREAD

**Issue by actioncrypto** [geduldig/TwitterAPI#66]
Hello,

Perhaps I'm missing something obvious... but it would appear the iterator returned for a stream is from a never-ending while True loop, therefore I can't find an easy way to kill the stream.

Is this the case? I tried feeding an authenticated API into a function that merely does:

    def streamTweet():
        r = api.request('user')
	        for item in r:
		        print item['text'] if 'text' in item else item

    t = threading.Thread(target=streamTweet, args=(api,))
    t.start()

and it would seem there is no clear (correct) way to stop the thread, or, if not using a thread: disconnect the stream... any ideas?  

If I were to drop into a shell, authenticate an api, and then execute the code in the `streamTweet` function manually, it would block the rest of the console/program... I'd like this to happen in the background if that makes sense...

**Comment by geduldig** [comment]
Hi,
I think you are right. There's no good way to disconnect. Stay tuned...

**Comment by geduldig** [comment]
I modified your code so it can properly close the stream. The following works in a Python console...

    def streamTweet(api):
        r = api.request('user')
        api.stream = r
        try:
            for item in r:
                print(item['text'] if 'text' in item else item)
        except AttributeError:
            print('***CLOSED***')

    t = threading.Thread(target=streamTweet, args=(api,))
    t.start()

Then close the stream with this...

    def closeStream(api):
        print('***CLOSING***')
        api.stream.response.raw.close()

    t = threading.Thread(target=closeStream, args=(api,))
    t.start()

It takes about 30 seconds to close, but it happens in the background.

For some reason `closeStream()` blocks with Python 3 and doesn't block with Python 2. The above code works with either. Though, if you are using Python 2 it is not necessary to call `closeStream()` in a thread. You can simply call:

    closeStream(api)

If you try it out, let me know how it works for you.

**Comment by geduldig** [comment]
TwitterAPI 2.3.4 now incorporates some of the above code for closing streams. The example can now be simplified as follows:

    def streamTweet(api):
        r = api.request('user')
        api.stream = r
        for item in r:
            print(item['text'] if 'text' in item else item)

    t = threading.Thread(target=streamTweet, args=(api,))
    t.start()

Close the stream:

    t = threading.Thread(target=api.stream.close)
    t.start()
