### ISSUE TITLE
Bug report : upload a big size video(more than 5MB) to twitter is not working

### ISSUE THREAD

**Issue by zhexiao** [geduldig/TwitterAPI#67]
```python
r = self.api.request('media/upload', {'command':'INIT', 'media_type':'video/mp4', 'total_bytes':nbytes})
media_id = r.json()['media_id']

self.api.request('media/upload', {'command':'APPEND', 'media_id':media_id, 'segment_index':0}, {'media':data})

self.api.request('media/upload', {'command':'FINALIZE', 'media_id':media_id})
```

this code is only works when your video is below 5MB. When you want to upload a big video to twitter, you have to chunk it to multiple segments.

**Comment by geduldig** [comment]
This code was meant to provide a simple example. If you want to write a patch that does chunking I will merge it.

**Comment by zhexiao** [comment]
OK. I had chucking the upload, let me push it

**Comment by zhexiao** [comment]
The updates is as follows:
```python
# chuck upload
segment_id = 0
while True:
    # 4MB per chunk for video upload
    chunk = file.read(4*1024*1024) 
    if chunk == '':
        break

    self.api.request('media/upload', {'command':'APPEND', 'media_id':media_id, 'segment_index':segment_id}, {'media':chunk})
    segment_id = segment_id + 1
```

**Comment by geduldig** [comment]
Thanks! Would you want to make this into a pull request?

**Comment by zhexiao** [comment]
Thanks, But i do not have permission to push branch.

**Comment by geduldig** [comment]
`pull` not `push`. I think [this](http://yangsu.github.io/pull-request-tutorial/) explains it.

**Comment by miguelripoll** [comment]
@zhexiao your path didn't work for me. I created a pull request with the code that worked for me here https://github.com/geduldig/TwitterAPI/issues/67
