### ISSUE TITLE
How to insert new line into a status update?

### ISSUE THREAD

**Issue by miguelripoll** [geduldig/TwitterAPI#68]
I'm trying to use \n or %0A but it doesn't work, anyone knows?

**Comment by geduldig** [comment]
`\n` worked for me. I used [this example](https://github.com/geduldig/TwitterAPI/blob/master/examples/post_tweet.py).

**Comment by miguelripoll** [comment]
I'm sorry for this one. This is the behavior from raw_input, not a bug from the project.

Thanks you.
