### ISSUE TITLE
Stream issues & read timeouts

### ISSUE THREAD

**Issue by actioncrypto** [geduldig/TwitterAPI#72]
Code was working fine for awhile... no changes to it, then all of sudden for past couple hours, can no longer get any responses from Twitter streams... Very baffled

Seems to be related to read errors on HTTPS connections? Happens for both user stream and also normal tweet streaming... I have been trying over past couple days to get the Fault Tolerant Stream snippets you had written implemented, however the interaction with Twitter's API seems to be kicking my ass.... can not figure out why it's breaking.

Getting errors like this:
`TwitterAPI.TwitterError.TwitterConnectionError: HTTPSConnectionPool(host='userstream.twitter.com', port=443): Read timed out. (read timeout=90)`

`TwitterAPI.TwitterError.TwitterConnectionError: HTTPSConnectionPool(host='stream.twitter.com', port=443): Read timed out. (read timeout=90)`

Will reliably break with even this simple example code:

    print 'before'
	r = api.request('user')
	api.stream = r
	for item in r:
		print(item['text'] if 'text' in item else item)
	print 'after'

gives:

    $ ./tweet_commander.py 
    before
    WARNING:root:<class 'requests.exceptions.ReadTimeout'> HTTPSConnectionPool(host='userstream.twitter.com', port=443): Read timed out. (read timeout=90)
    Traceback (most recent call last):
      File "./tweet_commander.py", line 400, in <module>
        r = api.request('user')
      File "/Users/XXXX/.pyenv/versions/2.7.9/lib/python2.7/site-packages/TwitterAPI/TwitterAPI.py", line 124, in request
        raise TwitterConnectionError(e)
    TwitterAPI.TwitterError.TwitterConnectionError: HTTPSConnectionPool(host='userstream.twitter.com', port=443): Read timed out. (read timeout=90)

`api` is correctly authorized, as i can pull home timeline fine.... This code works perfectly, print's the `after` and continues on to rest of program:

    print 'before'
	r = api.request('statuses/home_timeline', {'count': 5})
	for item in r.get_iterator():
		if 'text' in item:
			print item['text']
	print 'after'

any ideas what has failed and what i need to fix?

**Comment by geduldig** [comment]
Check twitter's status page. The stream has down this week sporadically.

**Comment by actioncrypto** [comment]
Indeed! It appears to have fixed itself now. Thanks much, I was really confused thinking the code was at fault
