### ISSUE TITLE
Video Upload Not Working

### ISSUE THREAD

**Issue by pietrop** [geduldig/TwitterAPI#73]
I am trying the video upload example 
https://github.com/geduldig/TwitterAPI/blob/master/examples/upload_video.py

but I get an error: 

```
400
{"errors":[{"code":44,"message":"media parameter is invalid."}]}
```

any suggestions?

**Comment by geduldig** [comment]
Yeah, it means your video does not comply with Twitter's specs.  They are spelled out here: https://dev.twitter.com/rest/public/uploading-media

**Comment by djedi** [comment]
I've tried several videos that comply with the published specs and I haven't gotten one of them to work. Do you have any examples that *should* work?

While I can't get a video to publish via the API, *sometimes* I can get it to publish via the web interface (sometimes not).

Ones that I can't get to upload via the API or the web interface, I can save to dropbox, then save to my iphone and post vial the iphone twitter app.

Which of these sample vidoes (if any) would you say should work? http://www.sample-videos.com/

**Comment by pietrop** [comment]
I still couldn't get this python library to work, but I can tell you that if you are looking for a sample video this [one](https://dl.dropboxusercontent.com/u/449999/debate_test_trimmed.mp4) I know for sure that it works (I've used it with the node twitter API)

Also I know that is a javascript/node module so probably not useful for you but [this is the module](https://github.com/pietrop/quickQuoteNode/blob/master/lib/interactive_video_components/export/twitter_video/trim_video.js) I used to trim that video to meet the [twitter video specs](https://dev.twitter.com/rest/public/uploading-media#videorecs) using an ffmpeg wraper.

Hope this helps

**Comment by geduldig** [comment]
This [clip](https://vimeo.com/139741399) worked for me using this [example](https://github.com/geduldig/TwitterAPI/blob/master/examples/upload_video.py).

I tried a couple of clips from http://www.sample-videos.com/, and none worked. Twitter returns an `UnsupportedMedia` error. The reason may be that the audio in these clips is surround sound.

**Comment by djedi** [comment]
Ah thank you! I finally got a video to upload with the API! Still I think their video API is pretty finicky.

**Comment by djedi** [comment]
In case anyone else is curious, I was able to take the first sample video on that site, run it through ffmpeg to convert the audio to 2 channel and get it to upload.

`ffmpeg -i SampleVideo_720x480_1mb.mp4 -ac 2 test.mp4`
