### ISSUE TITLE
StreamingAPI Get all @Mentions returns TwitterRequestError 406

### ISSUE THREAD

**Issue by DeastinY** [geduldig/TwitterAPI#75]
I am trying to get all @ mentions, but 

`for msg in api.request('statuses/filter', {'replies': 'all'}): `

returns a

`TwitterAPI.TwitterError.TwitterRequestError: Twitter request failed (406)`

I looked at the Twitter API but could not see any general usage errors.

Twitter documentation:

> By default @replies are only sent if the current user follows both the sender and receiver of the reply. For example, consider the case where Alice follows Bob, but Alice doesn’t follow Carol. By default, if Bob @replies Carol, Alice does not see the Tweet. This mimics twitter.com and api.twitter.com behavior. To have such Tweets returned in a streaming connection, specify replies=all when connecting.

**Comment by geduldig** [comment]
This is because `replies=all` only works with `user` and  `site` streams but not `filter` streams. In the [documentation](https://dev.twitter.com/streaming/overview/request-parameters), the line just above your quote says: "Available on GET user and GET site."

**Comment by DeastinY** [comment]
Thanks a bunch for the super fast reply !

**Comment by DeastinY** [comment]
Just for completeness: 
`api.request('user', {'replies': 'all'})`
