### ISSUE TITLE
Can't perform GET of the media/upload endpoint

### ISSUE THREAD

**Issue by bcattle** [geduldig/TwitterAPI#76]
Hey, due to Twitter increasing the allowed video length to 140 secs, there's a new asyncronous processing step that may or may not take place when you upload a video. You can read about it [here](https://dev.twitter.com/rest/media/uploading-media#chunkedupload), see under  FINALIZE -> "Async finalize which requires subsequent STATUS call".

Basically, you perform the chunked upload as before, then if the POST `media/upload` response contains the field `processing_info`, you need to poll to determine when the media is done processing, before you can use the `media_id` in a tweet.

This polling is accomplished by doing a [GET of the `media/upload` endpoint](https://dev.twitter.com/rest/reference/get/media/upload-status). This GET operation isn't currently permitted by the TwitterAPI library. The library [hard-codes the POST HTTP method](https://github.com/geduldig/TwitterAPI/blob/master/TwitterAPI/constants.py#L105) for the `media/upload` endpoint. 

I needed to get this working quickly, so I forked the library and added a `method_override` argument to the `request()` function to allow this. You can see it [here](https://github.com/bcattle/TwitterAPI/blob/master/TwitterAPI/TwitterAPI.py#L86). 

I'm not sure if this is the best way to solve this problem. If it is I can create a PR. 
Thanks.

**Comment by geduldig** [comment]
Are doing something like this example?
https://github.com/geduldig/TwitterAPI/blob/master/examples/upload_video.py

What version of TwitterAPI are you using?

**Comment by bcattle** [comment]
Yeah I'm doing exactly what's in the example. The call to 'FINALIZE' on line 53, can now return a response like the following, which indicates that an asynchronous processing step is to be performed:

    "processing_info": {
        "state": "pending",
        "check_after_secs": 5 // check after 5 seconds for update using STATUS command
      }

If you get this response, you need to make subsequent GET calls to 'media/upload' until the "state" becomes "failed" or "succeeded". 

See [here](https://dev.twitter.com/rest/media/uploading-media) for more information, down under "STATUS". 

I'm using the latest version of master.

**Comment by geduldig** [comment]
Okay, I had some more time to look at this, and I see what you are talking about. Your patch looks good, but I want to first see if I prefer any alternatives. Thank you for pointing this out.

**Comment by geduldig** [comment]
I like your solution over other alternatives. If you make a pull request I'll add it. Thanks again!
