### ISSUE TITLE
Streaming when a user is mentionned in a tweet

### ISSUE THREAD

**Issue by guinslym** [geduldig/TwitterAPI#78]
Hi! I have a list of Twitter handle (screen_name without the `@`)  I wanted to track each time one of these users are **mentionned** in a tweet. 
I use this expression `r = api.request('statuses/filter', {'track': TRACK_TERM})` so that I can stream those tweets and I let the script run for a week. 

`TRACK_TERM = ['AaronWherry',''kady",..]`

Now I realize that I've tweets that doesn't mention the targeted users (TRACK_TERM)  i.e. [kady](https://twitter.com/kady) is in my TRACK_TERM so I would like to retrieve [tweets](https://twitter.com/SherryRomanado/status/768182452049350656) that mention her Twitter handle but I also getting tweets like [this one](https://twitter.com/AdrianeWelford/status/741381221150822401) that have 'kady' in the tweets but it doesn't mention the real 'kady'

```
 "entities": {
        "urls": [],
        "hashtags": [{
        ...
        }],
        "symbols": [],
        "user_mentions": []
    },
```

So my question is how to target only users that are in my TRACK_TERM.  I can't track by id `210462857140252672` because it will only show the tweets of the targeted users and I, I want  to retrieve only when a user is mentioning a targeted user.

**Comment by geduldig** [comment]
Hi -
What not track user names with the '@' prefix?

**Comment by guinslym** [comment]
Thanks @geduldig for your answer  ! I didn't think about that. Everything works fine now! :+1:
