### ISSUE TITLE
status does not work and gives error 

### ISSUE THREAD

**Issue by nihitx** [geduldig/TwitterAPI#88]
Hi I am trying the reach estimate api by twitter and it does not seem to work.
Getting the error down 
`Endpoint "%s" unsupported' % endpoint)`
This is what I am trying to do.
```
stats = api.request('stats/accounts/123456?entity=LINE_ITEM&entity_ids=8u94t&start_time=2017-05-19&end_time=2017-05-26&granularity=TOTAL&placement=ALL_ON_TWITTER&metric_groups=ENGAGEMENT')
stats_estimate = stats.json()
pprint(stats_estimate)
```

**Comment by geduldig** [comment]
I don't see this endpoint on the twitter dev website. Can you post a link to the doc for this endpoint?

**Comment by geduldig** [comment]
Ignore my last comment..

**Comment by nihitx** [comment]
@geduldig anything yet?

**Comment by geduldig** [comment]
The endpoint you are using is part of the Ads API. I don't have access to this API for testing but I'll update the 'constants.py' file sometime this week -- unless you want to submit this as a patch :)

**Comment by nihitx** [comment]
I rather wait for you :D

**Comment by geduldig** [comment]
Have you applied for access to the Ads API as explained [here](https://developer.twitter.com/en/docs/ads/general/overview)? I would need you to test since I do not have access myself.

**Comment by nihitx** [comment]
@geduldig  Yes I did, waiting for a reply from twitter.

**Comment by geduldig** [comment]
Let me know when/if you hear back from Twitter, and I will reopen this issue.

**Comment by nihitx** [comment]
Hi Geduldig! 
So I got access finally and this is what I did 
adsapi = api.request('stats/accounts/:%d' % 30626658) 
And updated the constants.py like this
# ADS API

**Comment by geduldig** [comment]
It's a little more involved than I thought because the Ads API uses a different sub-domain. I'll have to make another change to TwitterAPI.py. I'll let you know when you can test it.

**Comment by nihitx** [comment]
Perfect! Thanks!

**Comment by geduldig** [comment]
I added the Ads endpoints to `constants.py` and made a change to `TwitterAPI.py`. I didn't update the project at pypi.python.org, so get them from github for now. Let me know how the testing goes. I'm not able to test.

**Comment by geduldig** [comment]
Any feedback from testing?
