### ISSUE TITLE
Support for new character limit?

### ISSUE THREAD

**Issue by youngsol** [geduldig/TwitterAPI#89]
Twitter now supports 280 character limit with extended mode.
How can I use this feature? Is this possible without modificaion of this package?
https://developer.twitter.com/en/docs/tweets/tweet-updates

**Comment by geduldig** [comment]
Yes, you can get extended tweets. It is documented [here](https://developer.twitter.com/en/docs/tweets/tweet-updates).

When you call `search/tweets` simply supply this parameter: `tweet_mode=extended`. Then, get the extended tweet text in this field: `full_text`.
