### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by meshubhama01** [geduldig/TwitterAPI#90]
Traceback (most recent call last):
  File "C:/Users/SHUBHAM/Desktop/learn/twtest1.py", line 21, in <module>
    print(item['text'] if 'text' in item else item)
UnicodeEncodeError: 'UCS-2' codec can't encode characters in position 44-44: Non-BMP character not supported in Tk

**Comment by geduldig** [comment]
Your code happened to download a tweet containing Unicode characters that are not supported in the environment your code is running. You will need to find out how your particular environment supports Unicode.
