### ISSUE TITLE
TwitterConnectionError on streaming uploads

### ISSUE THREAD

**Issue by HammadH** [geduldig/TwitterAPI#93]
Hi, 

I want to be able to change the TIMEOUTS in constants.py from 5 to 10 seconds to avoid this. I tested and it works. Have a pull request ready to read these constants from the environment, if not set defaults. Please assist.

Thanks

**Comment by geduldig** [comment]
You shouldn't have to change the timeout. 5 seconds a long time. If you want, you can post a concise code example that raises `TwitterConnectionError` when using a second TIMEOUTS, and I'll take a look.

There was [this issue (#85)](https://github.com/geduldig/TwitterAPI/pull/85) which may be similar to yours. It turned out the problem was with the ISP. You might trying running your code through a different ISP.

**Comment by Roach** [comment]
This issue is valid if you're uploading a large (5mb+) image over a slow connection.

I'm running into this and manually overriding `CONNECTION_TIMEOUT` in my local instance of TwitterAPI.

**Comment by geduldig** [comment]
Before I add such a feature, can you explain what the downside is of manually overriding as you are now doing? I could imagine that manually overriding is actually the best solution. For instance, on machines with slow connections, you would want to set CONNECTION_TIMEOUT to a larger value. This way all code that runs on this machine will use an appropriate timeout. I guess the question is, if you are distributing your code to computers with various connection speeds, where do you want to set the timeout? Do you set it in every application, or do you set it once globally for all applications?

**Comment by Roach** [comment]
Having to manually override by modifying files in `site-packages` means that any changes will be overwritten the next time I update the lib. It'd be great if I could pass it in when instantiating the library or assign it to an environmental variable.

For a distributed scenario, you'd set it either in a config file and pull in when the app loads or assign it as a global env var when the app itself is deployed.

**Comment by geduldig** [comment]
Okay. I'm considering moving all the _TIMEOUT constants into the TwitterAPI class as statics that can be overridden...

**Comment by geduldig** [comment]
Please try out the latest version, 2.5.9. You should be able to do the following to increase the timeout.

TwitterAPI.CONNECTION_TIMEOUT = 20
