### ISSUE TITLE
get the following number and comment number,forward number

### ISSUE THREAD

**Issue by liberty123** [geduldig/TwitterAPI#94]
Can this API get these?

**Comment by geduldig** [comment]
Please take a look at the Twitter API docs. 

You can get number of followers from `follower_count` in the [user object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/user-object).

You can get number of replies from `replay_count` in the [tweet object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object).
