### ISSUE TITLE
How to get more tweets in each search?

### ISSUE THREAD

**Issue by theAmouie** [geduldig/TwitterAPI#95]
Currently, when I search it gets me limited number of tweets, how can I get more as result?

**Comment by geduldig** [comment]
Post the request you are using.

**Comment by geduldig** [comment]
Use the `count` parameter with the `search/tweets` request. 
If you need more info, here is the doc: https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets.html
