### ISSUE TITLE
Sending empty query

### ISSUE THREAD

**Issue by bashir4909** [geduldig/TwitterAPI#97]
If one wants to get tweets with no search keyword, it can be done according to this page 
https://developer.twitter.com/en/docs/tweets/rules-and-filtering/guides/how-to-build-a-query
The request would be something like https://api.twitter.com/1.1/search/tweets.json?q=&geocode=-22.912214,-43.230182,1km&lang=pt&result_type=recent
Seems like api.request do not work if you put 
can you support it?

**Comment by geduldig** [comment]
It is supported. You just need to use empty single or double quotes like this: `q=''`.

For example,

`r = api.request('search/tweets', {'q':'', 'geocode':'40,-74,10mi'})`
